
import { PrismaClient } from '@prisma/client';

// ----------------------------------------------------------------------
// Prisma Client Singleton
// ----------------------------------------------------------------------

const prismaClientSingleton = () => {
    return new PrismaClient();
};

declare global {
    var prisma: undefined | ReturnType<typeof prismaClientSingleton>;
}

const db = globalThis.prisma ?? prismaClientSingleton();

export default db;

if (process.env.NODE_ENV !== 'production') globalThis.prisma = db;

// ----------------------------------------------------------------------
// Re-export generated types
// ----------------------------------------------------------------------

export * from '@prisma/client';

// ----------------------------------------------------------------------
// Manual Type Definitions for JSON Fields
// (These structures are stored in JSON columns and not generated by Prisma)
// ----------------------------------------------------------------------

// Source Data Type
// In Prisma, Source.data is JsonValue. We cast it to this type when needed.
export type SourceDataRow = Record<string, unknown>;

// Quality Intelligence Types
// stored in JSON or computed on the fly? QualityIntelligence is a Model now.
// But some fields like sampleValues in ColumnMeta are JSON.

// Column Intelligence
export interface ColumnMetaSampleValues {
    values: unknown[];
}

// Relationship Registry Types (Module 4D-A)
// Stored in RelationshipRegistry.entries (Json)

export type MatchType = 'NAME_MATCH' | 'VALUE_OVERLAP';

export interface ConfidenceFactors {
    nameScore: number;           // 0-1: Column name similarity
    overlapScore: number;        // 0-1: Value overlap percentage
    uniquenessScore: number;     // 0-1: PK uniqueness (should be ~1.0)
    dataTypeScore: number;       // 0-1: Data type compatibility
}

export type RelationshipType = 'PRIMARY_KEY' | 'FOREIGN_KEY' | 'LOOKUP';
export type DetectionMethod = 'NAME_MATCH' | 'VALUE_OVERLAP' | 'UNIQUENESS' | 'AI_VALIDATED' | 'COMPOSITE';
export type JoinCardinality = 'ONE_TO_ONE' | 'ONE_TO_MANY' | 'MANY_TO_MANY';

export interface AIValidationResult {
    validated: boolean;
    reasoning: string;
    adjustedConfidence?: number;
}

export interface RelationshipEntry {
    id: string;
    projectId: string;
    sourceTableId: string;
    sourceTableName: string;
    sourceColumn: string;
    targetTableId: string;
    targetTableName: string;
    targetColumn: string;
    relationshipType: RelationshipType;
    joinCardinality: JoinCardinality;
    confidence: number;
    detectionMethod: DetectionMethod;
    confidenceFactors: ConfidenceFactors;
    aiValidation?: AIValidationResult;
    explanation: string;          // Human-readable explanation
    detectedAt: Date | string;    // Date or string if from JSON
}

// KPI Lineage Registry Types (Module 4D-B)
// Stored in KPILineageRegistry.entries (Json)

export interface KPISourceContribution {
    sourceId: string;
    sourceName: string;
    columns: string[];
    role: 'PRIMARY' | 'JOINED' | 'AGGREGATED';
}

export interface KPIJoin {
    leftSource: string;
    rightSource: string;
    leftColumn: string;
    rightColumn: string;
    joinType: 'INNER' | 'LEFT' | 'RIGHT' | 'FULL';
}

export interface KPIAggregation {
    function: 'SUM' | 'AVG' | 'COUNT' | 'COUNT_DISTINCT' | 'MIN' | 'MAX';
    column: string;
    sourceId: string;
}

export interface KPIJoinPath {
    relationshipId: string;               // Reference to RelationshipEntry from 4D-A
    sourceTable: string;
    sourceColumn: string;
    targetTable: string;
    targetColumn: string;
    joinType: 'INNER' | 'LEFT' | 'RIGHT' | 'FULL';
    confidence: number;
}

export interface KPILineageEntry {
    id: string;
    projectId: string;
    kpiId: string;
    kpiName: string;
    domain: string;
    formula: string;
    category: string;
    sources: KPISourceContribution[];
    joinPaths: KPIJoinPath[];             // From 4D-A RelationshipRegistry
    aggregations: KPIAggregation[];
    technicalExplanation: string;         // Formula-based explanation
    businessExplanation: string;          // Human-friendly explanation
    aiEnhanced: boolean;                  // Was explanation enhanced by AI?
    confidence: number;
    tracedAt: Date | string;
}

export interface KPILineage {
    kpiId: string;
    kpiName: string;
    formula: string;
    category: string;
    sources: KPISourceContribution[];
    joins: KPIJoin[];
    aggregations: KPIAggregation[];
    explanation: string;
    confidence: number;
    tracedAt: Date | string;
}

// Data Lineage Types (Module 4D)
// Stored in DataLineage.entityGraph (Json)

export interface EntityNode {
    id: string;                          // Source ID
    name: string;                        // Table/file name
    entityType: string;                  // Inferred entity type: 'customers', 'orders', etc.
    columns: string[];
    primaryKeyCandidate: string | null;
    foreignKeys: ForeignKeyCandidate[];
}

export interface ForeignKeyCandidate {
    column: string;
    referencedEntity: string;            // Source ID it likely references
    referencedColumn: string;
    confidence: number;
}

export interface EntityEdge {
    id: string;
    fromNode: string;                    // Source ID
    toNode: string;                      // Source ID
    joinType: 'ONE_TO_ONE' | 'ONE_TO_MANY' | 'MANY_TO_MANY';
    joinCondition: { fromColumn: string; toColumn: string };
    confidence: number;
}

export interface EntityRelationshipGraph {
    projectId: string;
    nodes: EntityNode[];
    edges: EntityEdge[];
    createdAt: Date | string;
}

// KPI Discovery Types
// Stored in KPIDiscovery.computableKPIs (Json)

export interface ComputableKPI {
    id: string;
    name: string;
    formula: string;
    columns: string[];
    confidence: number;
}

// ─── Relational KPI Blueprint Types ─────────────────────────────────────────
// Explicit interfaces matched to the Prisma schema — no import needed.
// These are the ground-truth shapes for Module 4 ↔ Module 5 data contracts.

export type AggregationFunction = 'SUM' | 'COUNT' | 'COUNT_DISTINCT' | 'AVG' | 'MIN' | 'MAX';

export interface AggregationRule {
    id: string;
    kpiId: string;
    function: AggregationFunction;
    column: string;
}

export interface GroupByDefinition {
    id: string;
    kpiId: string;
    column: string;
}

export interface LineageDefinition {
    id: string;
    kpiId: string;
    formula: string;
    tables: string[];   // Json -> string[] at runtime
    joins: KPIJoinPath[];    // Json -> JoinPath[] at runtime
}

export interface ApprovedKPI {
    id: string;
    blueprintId: string;
    kpiLibraryId: string | null;
    name: string;
    description: string | null;
    sourceTable: string;
    category: string;
    createdAt: Date;
    updatedAt: Date;
}

export interface KPIBlueprint {
    id: string;
    projectId: string;
    domain: string;
    version: number;
    isLocked: boolean;
    lockedAt: Date | null;
    lockedBy: string | null;
    createdAt: Date;
    updatedAt: Date;
}

// Hydrated shapes with relations resolved
export type ApprovedKPIWithRelations = ApprovedKPI & {
    aggregations: AggregationRule[];
    groupBys: GroupByDefinition[];
    lineage: LineageDefinition | null;
};

export type BlueprintWithKPIs = KPIBlueprint & {
    kpis: ApprovedKPIWithRelations[];
};

// ─── Legacy compatibility shim ───────────────────────────────────────────────
// Flat shape for the execution engine and lineage modules.
// Must be explicitly constructed from ApprovedKPIWithRelations using flattenKPI().
export interface FlatApprovedKPI {
    id: string;
    name: string;
    category: string;
    sourceTable: string;
    aggregations: { function: string; column: string }[];
    groupBy: string | null;
    lineage: {
        tables: string[];
        joins: KPIJoinPath[];
        formula: string;
    };
}
