import { executeGoalPipeline } from '../src/lib/module-7/goal-engine';

const useCases = [
    // E-Commerce
    { query: "Increase Average Order Value by 15% before Black Friday.", domain: "ECOMMERCE", locations: ['California', 'Texas', 'New York'] },
    { query: "Reduce cart abandonment rate by 10% over the next 30 days.", domain: "ECOMMERCE", locations: ['Global'] },
    
    // SaaS
    { query: "Increase Trial-to-Paid conversion rate by 15% in Q3.", domain: "SAAS", locations: ['NA', 'EMEA', 'APAC'] },
    { query: "Reduce customer churn rate by 5% this year.", domain: "SAAS", locations: ['Enterprise', 'SMB'] },

    // Finance
    { query: "Reduce non-performing loan ratio by 2% next quarter.", domain: "FINANCE", locations: ['Retail Banking', 'Corporate'] },
];

async function runTests() {
    console.log("🚀 Starting Module 7 Pipeline Tests with Dummy Data\n");
    
    for (const [index, useCase] of useCases.entries()) {
        console.log(`========================================================`);
        console.log(`Test Case ${index + 1}: ${useCase.domain}`);
        console.log(`Query: "${useCase.query}"`);
        console.log(`Locations: ${useCase.locations.join(', ')}`);
        console.log(`========================================================`);
        
        try {
            const canvas = await executeGoalPipeline(useCase.query, useCase.domain, useCase.locations, (stage) => {
                // process.stdout.write(`-> ${stage} `);
            });
            
            console.log(`\n✅ Pipeline Succeeded in ${canvas.pipelineMs}ms`);
            
            // 1. Parsed Goal
            console.log(`\n🎯 1. PARSED GOAL:`);
            console.log(`  - Target Metric: ${canvas.goal.targetMetric} (${canvas.goal.changeDirection})`);
            console.log(`  - Target Value: ${canvas.goal.targetValue}`);
            console.log(`  - Timeframe: ${canvas.goal.timeframe}`);
            
            // 2. Decomposed Factors
            console.log(`\n🧩 2. DECOMPOSITION (${canvas.decomposed.formula}):`);
            canvas.decomposed.factors.forEach(f => {
                console.log(`  - [${f.metric}]: requires ${f.requiredChange}`);
                console.log(`    > ${f.description}`);
            });
            
            // 3. Top Actions Generated by AI
            console.log(`\n💡 3. AI-GENERATED STRATEGIES (Top ${canvas.topActions.length}):`);
            canvas.topActions.forEach((a, i) => {
                console.log(`  ${i+1}. ${a.actionName} (Confidence: ${a.confidenceScore}%)`);
            });
            
            // 4. Scenarios
            console.log(`\n📋 4. EXECUTION SCENARIOS (For Top Action: ${canvas.scenarios[0]?.actionName}):`);
            canvas.scenarios[0]?.scenarios.forEach(s => {
                console.log(`  [${s.level.toUpperCase()}] - ${s.label}`);
                console.log(`  Cost: ${s.estimatedCost} | Timeline: ${s.timeline}`);
                console.log(`  Steps:`);
                s.executionPlan.forEach(step => console.log(`    - ${step}`));
            });
            
            // 5. Locations
            console.log(`\n🌍 5. LOCATION/SEGMENT SPLIT:`);
            canvas.locationSplits.forEach(l => {
                const tierMap: Record<string, string> = { 'HIGH': 'PREMIUM', 'MEDIUM': 'BALANCED', 'LOW': 'LEAN' };
                const assignedTier = tierMap[l.performanceTier];
                
                console.log(`  - ${l.locationName} (${l.performanceTier}):`);
                console.log(`    Goal: ${l.adjustedGoal}`);
                console.log(`    Strategy: Allocate ${assignedTier} resources`);
                console.log(`    Reason: ${l.tierReason}`);
            });
            
        } catch (e: any) {
            console.error(`\n❌ Pipeline Failed: ${e.message}`);
        }
        console.log(`\n`);
    }
}

runTests();
