// KPI Library - Master definitions for all 8 domains
// Module 4 Phase 4A — v2: aligned to real 25-column test-datasets
// ⚠️  ALL KPIs map to the ACTUAL 25 columns in test-datasets/[domain]/*.csv:
//   timestamp, record_id, entity_id, entity_segment, entity_region,
//   target_id, target_category, target_subcategory, event_style, event_channel,
//   status, metric_1_value, metric_2_time_ms, metric_3_rate, metric_4_physical,
//   metric_5_financial, flag_1_active, flag_2_priority, context_1, context_2,
//   tag_1, tag_2, version_code, coord_x, coord_y
//
// DOMAIN MEANINGS per column:
//   ecommerce  → metric_1=order_value, metric_2=latency_ms, metric_3=conversion_rate, metric_4=temp_warehouse, metric_5=profit
//   edtech     → metric_1=lesson_progress, metric_2=video_duration_ms, metric_3=completion_rate, metric_4=quiz_score, metric_5=revenue_per_session
//   retail     → metric_1=basket_value, metric_2=checkout_time_ms, metric_3=sell_through_rate, metric_4=footfall_density, metric_5=margin
//   saas       → metric_1=usage_events, metric_2=api_latency_ms, metric_3=retention_rate, metric_4=cpu_usage_pct, metric_5=mrr
//   finance    → metric_1=transaction_amount, metric_2=processing_time_ms, metric_3=approval_rate, metric_4=risk_score, metric_5=net_revenue
//   healthcare → metric_1=vitals_score, metric_2=wait_time_ms, metric_3=treatment_success_rate, metric_4=patient_temp, metric_5=claim_value
//   manufacturing → metric_1=units_produced, metric_2=cycle_time_ms, metric_3=yield_rate, metric_4=machine_temp, metric_5=production_cost
//   services   → metric_1=billable_hours, metric_2=response_time_ms, metric_3=sla_met_rate, metric_4=csat_score, metric_5=invoice_value

import type { DomainType } from '../prisma';
import { DOMAIN_ALIASES } from './semantic-column-aliases';

export interface KPIDefinition {
    id: string;
    name: string;
    domain: DomainType;
    description: string;
    requiredFields: string[];
    formulaTemplate: string;
    aggregationRules: { function: string; column: string }[];
    defaultVisualizationHint: string;
    columnAliases: Record<string, string[]>;
    category: string;
    priority: number;
    // Continuous-data fields for forecasting
    isContinuous?: boolean;
    forecastable?: boolean;
    sourceFiles?: string[]; // which of the 10 theme files this KPI applies to
}

/**
 * Helper to enrich a list of KPIs with the latest semantic aliases for their domain.
 */
function enrichKPIs(kpis: KPIDefinition[], domain: DomainType): KPIDefinition[] {
    const domainAliases = DOMAIN_ALIASES[domain] || {};
    return kpis.map(kpi => {
        const enhancedAliases: Record<string, string[]> = { ...kpi.columnAliases };
        for (const field of kpi.requiredFields) {
            const globalAliases = (domainAliases as any)[field] || [];
            if (globalAliases.length > 0) {
                enhancedAliases[field] = Array.from(new Set([...(enhancedAliases[field] || []), ...globalAliases]));
            }
        }
        return { ...kpi, columnAliases: enhancedAliases };
    });
}

// ─── E-COMMERCE ────────────────────────────────────────────────────────────────
// Files: ecommerce_transactions, interactions, operations, support, marketing,
//        feedback, finance, users, performance, system
// event_style: page_view, search, add_to_cart, checkout_start, purchase,
//              review_submit, return_request, support_chat, wishlist_add, promo_apply

const RAW_ECOMMERCE_KPIS: KPIDefinition[] = [
    // ── Revenue ──
    { id: 'ec-001', name: 'Total Revenue', domain: 'ECOMMERCE', description: 'Sum of all order values (metric_5_financial)', formulaTemplate: 'SUM(metric_5_financial)', aggregationRules: [{ function: 'SUM', column: 'metric_5_financial' }], defaultVisualizationHint: 'metric_card', requiredFields: ['metric_5_financial'], columnAliases: { metric_5_financial: ['profit', 'order_value', 'revenue', 'amount'] }, category: 'revenue', priority: 1, isContinuous: true, forecastable: true, sourceFiles: ['transactions', 'finance'] },
    { id: 'ec-002', name: 'Average Order Value', domain: 'ECOMMERCE', description: 'Average basket value per transaction', formulaTemplate: 'AVG(metric_1_value)', aggregationRules: [{ function: 'AVG', column: 'metric_1_value' }], defaultVisualizationHint: 'metric_card', requiredFields: ['metric_1_value'], columnAliases: { metric_1_value: ['order_value', 'basket_value', 'transaction_amount'] }, category: 'revenue', priority: 2, isContinuous: true, forecastable: true, sourceFiles: ['transactions'] },
    { id: 'ec-003', name: 'Revenue per Segment', domain: 'ECOMMERCE', description: 'Total revenue grouped by customer segment', formulaTemplate: 'SUM(metric_5_financial) GROUP BY entity_segment', aggregationRules: [{ function: 'SUM', column: 'metric_5_financial' }], defaultVisualizationHint: 'bar_chart', requiredFields: ['metric_5_financial', 'entity_segment'], columnAliases: { entity_segment: ['customer_segment', 'tier'] }, category: 'revenue', priority: 3, isContinuous: false, forecastable: false, sourceFiles: ['finance', 'users'] },
    { id: 'ec-004', name: 'Revenue by Channel', domain: 'ECOMMERCE', description: 'Revenue split by sales channel', formulaTemplate: 'SUM(metric_5_financial) GROUP BY event_channel', aggregationRules: [{ function: 'SUM', column: 'metric_5_financial' }], defaultVisualizationHint: 'bar_chart', requiredFields: ['metric_5_financial', 'event_channel'], columnAliases: { event_channel: ['channel', 'platform', 'source'] }, category: 'revenue', priority: 4, isContinuous: false, forecastable: false, sourceFiles: ['transactions', 'marketing'] },
    // ── Conversion ──
    { id: 'ec-005', name: 'Conversion Rate', domain: 'ECOMMERCE', description: 'Purchase events / total events', formulaTemplate: "COUNT(CASE WHEN event_style='purchase' THEN 1 END) / COUNT(record_id)", aggregationRules: [{ function: 'COUNT', column: 'record_id' }], defaultVisualizationHint: 'metric_card', requiredFields: ['event_style', 'record_id'], columnAliases: { event_style: ['event_type', 'action'], record_id: ['transaction_id', 'session_id'] }, category: 'conversion', priority: 5, isContinuous: true, forecastable: true, sourceFiles: ['interactions', 'transactions'] },
    { id: 'ec-006', name: 'Average Conversion Rate (metric_3)', domain: 'ECOMMERCE', description: 'Continuous conversion rate signal', formulaTemplate: 'AVG(metric_3_rate)', aggregationRules: [{ function: 'AVG', column: 'metric_3_rate' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_3_rate'], columnAliases: { metric_3_rate: ['conversion_rate', 'success_rate'] }, category: 'conversion', priority: 6, isContinuous: true, forecastable: true, sourceFiles: ['performance', 'transactions'] },
    { id: 'ec-007', name: 'Cart Abandonment Rate', domain: 'ECOMMERCE', description: 'add_to_cart events without purchase', formulaTemplate: "1 - (COUNT(CASE WHEN event_style='purchase' THEN 1 END) / COUNT(CASE WHEN event_style='add_to_cart' THEN 1 END))", aggregationRules: [{ function: 'COUNT', column: 'event_style' }], defaultVisualizationHint: 'metric_card', requiredFields: ['event_style'], columnAliases: { event_style: ['event_type', 'action'] }, category: 'conversion', priority: 7, isContinuous: true, forecastable: true, sourceFiles: ['interactions'] },
    // ── Performance ──
    { id: 'ec-008', name: 'System Latency (P50)', domain: 'ECOMMERCE', description: 'Median response time in milliseconds', formulaTemplate: 'AVG(metric_2_time_ms)', aggregationRules: [{ function: 'AVG', column: 'metric_2_time_ms' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_2_time_ms'], columnAliases: { metric_2_time_ms: ['latency', 'response_time_ms', 'duration_ms'] }, category: 'performance', priority: 8, isContinuous: true, forecastable: true, sourceFiles: ['system', 'performance'] },
    { id: 'ec-009', name: 'Peak Checkout Latency', domain: 'ECOMMERCE', description: 'Max latency during checkout events', formulaTemplate: "MAX(metric_2_time_ms) WHERE event_style='checkout_start'", aggregationRules: [{ function: 'MAX', column: 'metric_2_time_ms' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_2_time_ms', 'event_style'], columnAliases: { metric_2_time_ms: ['latency', 'response_time_ms'] }, category: 'performance', priority: 9, isContinuous: true, forecastable: true, sourceFiles: ['system', 'performance'] },
    { id: 'ec-010', name: 'Success Rate', domain: 'ECOMMERCE', description: 'Ratio of successful transactions', formulaTemplate: "COUNT(CASE WHEN status='Success' THEN 1 END) / COUNT(record_id)", aggregationRules: [{ function: 'COUNT', column: 'record_id' }], defaultVisualizationHint: 'metric_card', requiredFields: ['status', 'record_id'], columnAliases: { status: ['transaction_status', 'result'] }, category: 'performance', priority: 10, isContinuous: true, forecastable: true, sourceFiles: ['transactions', 'operations'] },
    // ── Customer ──
    { id: 'ec-011', name: 'Active Entities (Daily)', domain: 'ECOMMERCE', description: 'Unique customers active per day', formulaTemplate: 'COUNT(DISTINCT entity_id) GROUP BY DATE(timestamp)', aggregationRules: [{ function: 'COUNT_DISTINCT', column: 'entity_id' }], defaultVisualizationHint: 'line_chart', requiredFields: ['entity_id', 'timestamp'], columnAliases: { entity_id: ['customer_id', 'user_id'] }, category: 'customer', priority: 11, isContinuous: true, forecastable: true, sourceFiles: ['users', 'interactions'] },
    { id: 'ec-012', name: 'Customer Segment Distribution', domain: 'ECOMMERCE', description: 'Premium vs Standard vs Basic breakdown', formulaTemplate: 'COUNT(entity_id) GROUP BY entity_segment', aggregationRules: [{ function: 'COUNT', column: 'entity_id' }], defaultVisualizationHint: 'pie_chart', requiredFields: ['entity_id', 'entity_segment'], columnAliases: {}, category: 'customer', priority: 12, isContinuous: false, forecastable: false, sourceFiles: ['users'] },
    { id: 'ec-013', name: 'Revenue per Region', domain: 'ECOMMERCE', description: 'Geographic revenue distribution', formulaTemplate: 'SUM(metric_5_financial) GROUP BY entity_region', aggregationRules: [{ function: 'SUM', column: 'metric_5_financial' }], defaultVisualizationHint: 'bar_chart', requiredFields: ['metric_5_financial', 'entity_region'], columnAliases: { entity_region: ['region', 'geography'] }, category: 'customer', priority: 13, isContinuous: false, forecastable: false, sourceFiles: ['finance', 'marketing'] },
    // ── Marketing ──
    { id: 'ec-014', name: 'Promo Redemption Rate', domain: 'ECOMMERCE', description: 'promo_apply events over total events', formulaTemplate: "COUNT(CASE WHEN event_style='promo_apply' THEN 1 END) / COUNT(record_id)", aggregationRules: [{ function: 'COUNT', column: 'record_id' }], defaultVisualizationHint: 'metric_card', requiredFields: ['event_style', 'record_id'], columnAliases: {}, category: 'marketing', priority: 14, isContinuous: true, forecastable: true, sourceFiles: ['marketing'] },
    { id: 'ec-015', name: 'Wishlist to Purchase Rate', domain: 'ECOMMERCE', description: 'wishlist_add converted to purchase', formulaTemplate: "COUNT(CASE WHEN event_style='purchase' THEN 1 END) / COUNT(CASE WHEN event_style='wishlist_add' THEN 1 END)", aggregationRules: [{ function: 'COUNT', column: 'event_style' }], defaultVisualizationHint: 'metric_card', requiredFields: ['event_style'], columnAliases: {}, category: 'marketing', priority: 15, isContinuous: true, forecastable: true, sourceFiles: ['marketing', 'interactions'] },
    // ── Operations ──
    { id: 'ec-016', name: 'Return Request Rate', domain: 'ECOMMERCE', description: 'return_request events ratio', formulaTemplate: "COUNT(CASE WHEN event_style='return_request' THEN 1 END) / COUNT(record_id)", aggregationRules: [{ function: 'COUNT', column: 'record_id' }], defaultVisualizationHint: 'metric_card', requiredFields: ['event_style', 'record_id'], columnAliases: {}, category: 'operations', priority: 16, isContinuous: true, forecastable: true, sourceFiles: ['operations', 'support'] },
    { id: 'ec-017', name: 'Support Interaction Rate', domain: 'ECOMMERCE', description: 'Support chats per active customer', formulaTemplate: "COUNT(CASE WHEN event_style='support_chat' THEN 1 END) / COUNT(DISTINCT entity_id)", aggregationRules: [{ function: 'COUNT', column: 'event_style' }, { function: 'COUNT_DISTINCT', column: 'entity_id' }], defaultVisualizationHint: 'metric_card', requiredFields: ['event_style', 'entity_id'], columnAliases: {}, category: 'operations', priority: 17, isContinuous: true, forecastable: true, sourceFiles: ['support'] },
    { id: 'ec-018', name: 'Warehouse Temperature Avg', domain: 'ECOMMERCE', description: 'Average physical metric (warehouse conditions)', formulaTemplate: 'AVG(metric_4_physical)', aggregationRules: [{ function: 'AVG', column: 'metric_4_physical' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_4_physical'], columnAliases: { metric_4_physical: ['temperature', 'condition_score'] }, category: 'operations', priority: 18, isContinuous: true, forecastable: true, sourceFiles: ['operations', 'system'] },
    // ── Growth / Forecast ──
    { id: 'ec-019', name: 'Revenue Trend Over Time', domain: 'ECOMMERCE', description: 'Daily revenue for time-series forecasting', formulaTemplate: 'SUM(metric_5_financial) GROUP BY DATE(timestamp) ORDER BY DATE(timestamp)', aggregationRules: [{ function: 'SUM', column: 'metric_5_financial' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_5_financial', 'timestamp'], columnAliases: {}, category: 'growth', priority: 19, isContinuous: true, forecastable: true, sourceFiles: ['finance', 'transactions'] },
    { id: 'ec-020', name: 'Event Volume Trend', domain: 'ECOMMERCE', description: 'Total events per day for growth forecasting', formulaTemplate: 'COUNT(record_id) GROUP BY DATE(timestamp)', aggregationRules: [{ function: 'COUNT', column: 'record_id' }], defaultVisualizationHint: 'line_chart', requiredFields: ['record_id', 'timestamp'], columnAliases: {}, category: 'growth', priority: 20, isContinuous: true, forecastable: true, sourceFiles: ['transactions', 'interactions', 'system'] },
];
export const ECOMMERCE_KPIS = enrichKPIs(RAW_ECOMMERCE_KPIS, 'ECOMMERCE');

// ─── EDTECH ─────────────────────────────────────────────────────────────────────
// Files: edtech_transactions, interactions, operations, support, marketing,
//        feedback, finance, users, performance, system
// event_style: login, course_view, video_play, video_pause, quiz_start, quiz_submit,
//              assignment_upload, forum_post, certificate_download, support_ticket
// metric_1=lesson_progress (0-100), metric_2=video_duration_ms, metric_3=completion_rate,
// metric_4=quiz_score (20-25 mapped to 0-100%), metric_5=revenue_per_session

const RAW_EDTECH_KPIS: KPIDefinition[] = [
    { id: 'ed-001', name: 'Total Active Learners', domain: 'EDTECH', description: 'Unique students active in time window', formulaTemplate: 'COUNT(DISTINCT entity_id)', aggregationRules: [{ function: 'COUNT_DISTINCT', column: 'entity_id' }], defaultVisualizationHint: 'metric_card', requiredFields: ['entity_id'], columnAliases: { entity_id: ['student_id', 'user_id', 'learner_id'] }, category: 'engagement', priority: 1, isContinuous: true, forecastable: true, sourceFiles: ['users', 'interactions'] },
    { id: 'ed-002', name: 'Course Completion Rate', domain: 'EDTECH', description: 'Ratio of completion events', formulaTemplate: "COUNT(CASE WHEN event_style='certificate_download' THEN 1 END) / COUNT(DISTINCT entity_id)", aggregationRules: [{ function: 'COUNT', column: 'event_style' }, { function: 'COUNT_DISTINCT', column: 'entity_id' }], defaultVisualizationHint: 'metric_card', requiredFields: ['event_style', 'entity_id'], columnAliases: { event_style: ['event_type', 'action'] }, category: 'engagement', priority: 2, isContinuous: true, forecastable: true, sourceFiles: ['transactions', 'performance'] },
    { id: 'ed-003', name: 'Average Lesson Progress', domain: 'EDTECH', description: 'Continuous lesson progress score (0-100)', formulaTemplate: 'AVG(metric_1_value)', aggregationRules: [{ function: 'AVG', column: 'metric_1_value' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_1_value'], columnAliases: { metric_1_value: ['lesson_progress', 'completion_pct', 'progress'] }, category: 'engagement', priority: 3, isContinuous: true, forecastable: true, sourceFiles: ['interactions', 'performance'] },
    { id: 'ed-004', name: 'Average Video Duration Watched', domain: 'EDTECH', description: 'Avg time spent on video in ms', formulaTemplate: 'AVG(metric_2_time_ms)', aggregationRules: [{ function: 'AVG', column: 'metric_2_time_ms' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_2_time_ms'], columnAliases: { metric_2_time_ms: ['video_duration_ms', 'watch_time_ms', 'duration_ms'] }, category: 'engagement', priority: 4, isContinuous: true, forecastable: true, sourceFiles: ['interactions', 'performance'] },
    { id: 'ed-005', name: 'Quiz Pass Rate', domain: 'EDTECH', description: 'Continuous rate of successful quiz submits', formulaTemplate: 'AVG(metric_3_rate)', aggregationRules: [{ function: 'AVG', column: 'metric_3_rate' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_3_rate'], columnAliases: { metric_3_rate: ['completion_rate', 'pass_rate', 'success_rate'] }, category: 'performance', priority: 5, isContinuous: true, forecastable: true, sourceFiles: ['performance', 'feedback'] },
    { id: 'ed-006', name: 'Average Quiz Score', domain: 'EDTECH', description: 'Average student quiz score (scaled from metric_4)', formulaTemplate: 'AVG(metric_4_physical)', aggregationRules: [{ function: 'AVG', column: 'metric_4_physical' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_4_physical'], columnAliases: { metric_4_physical: ['quiz_score', 'test_score', 'grade'] }, category: 'performance', priority: 6, isContinuous: true, forecastable: true, sourceFiles: ['performance', 'feedback'] },
    { id: 'ed-007', name: 'Revenue per Session', domain: 'EDTECH', description: 'Financial value per learner session', formulaTemplate: 'AVG(metric_5_financial)', aggregationRules: [{ function: 'AVG', column: 'metric_5_financial' }], defaultVisualizationHint: 'metric_card', requiredFields: ['metric_5_financial'], columnAliases: { metric_5_financial: ['revenue_per_session', 'session_revenue'] }, category: 'revenue', priority: 7, isContinuous: true, forecastable: true, sourceFiles: ['finance', 'transactions'] },
    { id: 'ed-008', name: 'Total Platform Revenue', domain: 'EDTECH', description: 'Sum of all session revenues', formulaTemplate: 'SUM(metric_5_financial)', aggregationRules: [{ function: 'SUM', column: 'metric_5_financial' }], defaultVisualizationHint: 'metric_card', requiredFields: ['metric_5_financial'], columnAliases: { metric_5_financial: ['revenue', 'income'] }, category: 'revenue', priority: 8, isContinuous: true, forecastable: true, sourceFiles: ['finance'] },
    { id: 'ed-009', name: 'Platform Latency (P50)', domain: 'EDTECH', description: 'Median response time per event', formulaTemplate: 'AVG(metric_2_time_ms)', aggregationRules: [{ function: 'AVG', column: 'metric_2_time_ms' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_2_time_ms'], columnAliases: { metric_2_time_ms: ['latency', 'response_time_ms'] }, category: 'performance', priority: 9, isContinuous: true, forecastable: true, sourceFiles: ['system', 'performance'] },
    { id: 'ed-010', name: 'Dropout Rate', domain: 'EDTECH', description: 'Students who paused and never resumed', formulaTemplate: "COUNT(CASE WHEN event_style='video_pause' THEN 1 END) / COUNT(CASE WHEN event_style='video_play' THEN 1 END)", aggregationRules: [{ function: 'COUNT', column: 'event_style' }], defaultVisualizationHint: 'metric_card', requiredFields: ['event_style'], columnAliases: {}, category: 'retention', priority: 10, isContinuous: true, forecastable: true, sourceFiles: ['interactions'] },
    { id: 'ed-011', name: 'Assignment Submission Rate', domain: 'EDTECH', description: 'Assignments uploaded per enrolled learner', formulaTemplate: "COUNT(CASE WHEN event_style='assignment_upload' THEN 1 END) / COUNT(DISTINCT entity_id)", aggregationRules: [{ function: 'COUNT', column: 'event_style' }], defaultVisualizationHint: 'metric_card', requiredFields: ['event_style', 'entity_id'], columnAliases: {}, category: 'engagement', priority: 11, isContinuous: true, forecastable: true, sourceFiles: ['operations'] },
    { id: 'ed-012', name: 'Forum Engagement Rate', domain: 'EDTECH', description: 'Forum posts per active learner', formulaTemplate: "COUNT(CASE WHEN event_style='forum_post' THEN 1 END) / COUNT(DISTINCT entity_id)", aggregationRules: [{ function: 'COUNT', column: 'event_style' }], defaultVisualizationHint: 'metric_card', requiredFields: ['event_style', 'entity_id'], columnAliases: {}, category: 'engagement', priority: 12, isContinuous: true, forecastable: false, sourceFiles: ['interactions'] },
    { id: 'ed-013', name: 'Support Ticket Rate', domain: 'EDTECH', description: 'Support tickets raised per learner', formulaTemplate: "COUNT(CASE WHEN event_style='support_ticket' THEN 1 END) / COUNT(DISTINCT entity_id)", aggregationRules: [{ function: 'COUNT', column: 'event_style' }], defaultVisualizationHint: 'metric_card', requiredFields: ['event_style', 'entity_id'], columnAliases: {}, category: 'operations', priority: 13, isContinuous: true, forecastable: true, sourceFiles: ['support'] },
    { id: 'ed-014', name: 'Daily Active Learners Trend', domain: 'EDTECH', description: 'Time-series of daily unique learner logins', formulaTemplate: 'COUNT(DISTINCT entity_id) GROUP BY DATE(timestamp)', aggregationRules: [{ function: 'COUNT_DISTINCT', column: 'entity_id' }], defaultVisualizationHint: 'line_chart', requiredFields: ['entity_id', 'timestamp'], columnAliases: {}, category: 'growth', priority: 14, isContinuous: true, forecastable: true, sourceFiles: ['users', 'interactions'] },
    { id: 'ed-015', name: 'Revenue Growth Trend', domain: 'EDTECH', description: 'Daily revenue for forecasting', formulaTemplate: 'SUM(metric_5_financial) GROUP BY DATE(timestamp)', aggregationRules: [{ function: 'SUM', column: 'metric_5_financial' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_5_financial', 'timestamp'], columnAliases: {}, category: 'growth', priority: 15, isContinuous: true, forecastable: true, sourceFiles: ['finance'] },
];
export const EDTECH_KPIS = enrichKPIs(RAW_EDTECH_KPIS, 'EDTECH');

// ─── RETAIL ─────────────────────────────────────────────────────────────────────
// event_style: store_entry, aisle_browse, product_scan, fitting_room, pos_checkout,
//              loyalty_scan, return_item, kiosk_search, pickup_order, restock
// metric_1=basket_value, metric_2=checkout_time_ms, metric_3=sell_through_rate,
// metric_4=footfall_density, metric_5=margin

const RAW_RETAIL_KPIS: KPIDefinition[] = [
    { id: 'rt-001', name: 'Total Basket Value', domain: 'RETAIL', description: 'Sum of all basket values', formulaTemplate: 'SUM(metric_1_value)', aggregationRules: [{ function: 'SUM', column: 'metric_1_value' }], defaultVisualizationHint: 'metric_card', requiredFields: ['metric_1_value'], columnAliases: { metric_1_value: ['basket_value', 'sales', 'transaction_value'] }, category: 'revenue', priority: 1, isContinuous: true, forecastable: true, sourceFiles: ['transactions', 'finance'] },
    { id: 'rt-002', name: 'Average Basket Value', domain: 'RETAIL', description: 'Mean basket value per transaction', formulaTemplate: 'AVG(metric_1_value)', aggregationRules: [{ function: 'AVG', column: 'metric_1_value' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_1_value'], columnAliases: { metric_1_value: ['basket_value', 'aov'] }, category: 'revenue', priority: 2, isContinuous: true, forecastable: true, sourceFiles: ['transactions'] },
    { id: 'rt-003', name: 'Gross Margin', domain: 'RETAIL', description: 'Continuous margin from metric_5', formulaTemplate: 'AVG(metric_5_financial)', aggregationRules: [{ function: 'AVG', column: 'metric_5_financial' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_5_financial'], columnAliases: { metric_5_financial: ['margin', 'profit', 'gross_profit'] }, category: 'profitability', priority: 3, isContinuous: true, forecastable: true, sourceFiles: ['finance'] },
    { id: 'rt-004', name: 'Sell-Through Rate', domain: 'RETAIL', description: 'Continuous sell-through signal', formulaTemplate: 'AVG(metric_3_rate)', aggregationRules: [{ function: 'AVG', column: 'metric_3_rate' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_3_rate'], columnAliases: { metric_3_rate: ['sell_through_rate', 'inventory_turnover_rate'] }, category: 'operations', priority: 4, isContinuous: true, forecastable: true, sourceFiles: ['operations', 'performance'] },
    { id: 'rt-005', name: 'Checkout Time (Avg)', domain: 'RETAIL', description: 'Average pos_checkout duration', formulaTemplate: "AVG(metric_2_time_ms) WHERE event_style='pos_checkout'", aggregationRules: [{ function: 'AVG', column: 'metric_2_time_ms' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_2_time_ms', 'event_style'], columnAliases: { metric_2_time_ms: ['checkout_time_ms', 'dwell_time_ms'] }, category: 'performance', priority: 5, isContinuous: true, forecastable: true, sourceFiles: ['performance', 'transactions'] },
    { id: 'rt-006', name: 'Footfall Density', domain: 'RETAIL', description: 'Avg footfall measurement from metric_4', formulaTemplate: 'AVG(metric_4_physical)', aggregationRules: [{ function: 'AVG', column: 'metric_4_physical' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_4_physical'], columnAliases: { metric_4_physical: ['footfall_density', 'store_traffic'] }, category: 'volume', priority: 6, isContinuous: true, forecastable: true, sourceFiles: ['operations', 'interactions'] },
    { id: 'rt-007', name: 'Footfall Conversion Rate', domain: 'RETAIL', description: 'POS checkouts vs store entries', formulaTemplate: "COUNT(CASE WHEN event_style='pos_checkout' THEN 1 END) / COUNT(CASE WHEN event_style='store_entry' THEN 1 END)", aggregationRules: [{ function: 'COUNT', column: 'event_style' }], defaultVisualizationHint: 'metric_card', requiredFields: ['event_style'], columnAliases: {}, category: 'conversion', priority: 7, isContinuous: true, forecastable: true, sourceFiles: ['transactions', 'interactions'] },
    { id: 'rt-008', name: 'Return Rate', domain: 'RETAIL', description: 'return_item events vs checkouts', formulaTemplate: "COUNT(CASE WHEN event_style='return_item' THEN 1 END) / COUNT(CASE WHEN event_style='pos_checkout' THEN 1 END)", aggregationRules: [{ function: 'COUNT', column: 'event_style' }], defaultVisualizationHint: 'metric_card', requiredFields: ['event_style'], columnAliases: {}, category: 'operations', priority: 8, isContinuous: true, forecastable: true, sourceFiles: ['operations'] },
    { id: 'rt-009', name: 'Loyalty Scan Rate', domain: 'RETAIL', description: 'Loyalty program engagement', formulaTemplate: "COUNT(CASE WHEN event_style='loyalty_scan' THEN 1 END) / COUNT(CASE WHEN event_style='pos_checkout' THEN 1 END)", aggregationRules: [{ function: 'COUNT', column: 'event_style' }], defaultVisualizationHint: 'metric_card', requiredFields: ['event_style'], columnAliases: {}, category: 'marketing', priority: 9, isContinuous: true, forecastable: true, sourceFiles: ['marketing', 'users'] },
    { id: 'rt-010', name: 'Active Shoppers per Day', domain: 'RETAIL', description: 'Unique entities shopping daily', formulaTemplate: 'COUNT(DISTINCT entity_id) GROUP BY DATE(timestamp)', aggregationRules: [{ function: 'COUNT_DISTINCT', column: 'entity_id' }], defaultVisualizationHint: 'line_chart', requiredFields: ['entity_id', 'timestamp'], columnAliases: {}, category: 'customer', priority: 10, isContinuous: true, forecastable: true, sourceFiles: ['users', 'interactions'] },
    { id: 'rt-011', name: 'Revenue by Region', domain: 'RETAIL', description: 'Total basket value by region', formulaTemplate: 'SUM(metric_1_value) GROUP BY entity_region', aggregationRules: [{ function: 'SUM', column: 'metric_1_value' }], defaultVisualizationHint: 'bar_chart', requiredFields: ['metric_1_value', 'entity_region'], columnAliases: {}, category: 'revenue', priority: 11, isContinuous: false, forecastable: false, sourceFiles: ['finance', 'marketing'] },
    { id: 'rt-012', name: 'Revenue Trend (Daily)', domain: 'RETAIL', description: 'Daily sales for forecasting', formulaTemplate: 'SUM(metric_1_value) GROUP BY DATE(timestamp)', aggregationRules: [{ function: 'SUM', column: 'metric_1_value' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_1_value', 'timestamp'], columnAliases: {}, category: 'growth', priority: 12, isContinuous: true, forecastable: true, sourceFiles: ['transactions', 'finance'] },
    { id: 'rt-013', name: 'Restock Frequency', domain: 'RETAIL', description: 'Restock events per day', formulaTemplate: "COUNT(CASE WHEN event_style='restock' THEN 1 END) GROUP BY DATE(timestamp)", aggregationRules: [{ function: 'COUNT', column: 'event_style' }], defaultVisualizationHint: 'line_chart', requiredFields: ['event_style', 'timestamp'], columnAliases: {}, category: 'operations', priority: 13, isContinuous: true, forecastable: true, sourceFiles: ['operations'] },
    { id: 'rt-014', name: 'Pickup Order Rate', domain: 'RETAIL', description: 'Click-and-collect adoption', formulaTemplate: "COUNT(CASE WHEN event_style='pickup_order' THEN 1 END) / COUNT(CASE WHEN event_style='pos_checkout' THEN 1 END)", aggregationRules: [{ function: 'COUNT', column: 'event_style' }], defaultVisualizationHint: 'metric_card', requiredFields: ['event_style'], columnAliases: {}, category: 'operations', priority: 14, isContinuous: true, forecastable: true, sourceFiles: ['operations'] },
    { id: 'rt-015', name: 'Premium Segment Revenue Share', domain: 'RETAIL', description: 'Revenue from Premium vs others', formulaTemplate: "SUM(metric_1_value) WHERE entity_segment='Premium' / SUM(metric_1_value)", aggregationRules: [{ function: 'SUM', column: 'metric_1_value' }], defaultVisualizationHint: 'metric_card', requiredFields: ['metric_1_value', 'entity_segment'], columnAliases: {}, category: 'customer', priority: 15, isContinuous: false, forecastable: false, sourceFiles: ['users', 'finance'] },
];
export const RETAIL_KPIS = enrichKPIs(RAW_RETAIL_KPIS, 'RETAIL');

// ─── SAAS ─────────────────────────────────────────────────────────────────────
// event_style: login, dashboard_load, report_export, api_call, settings_update,
//              invite_user, upgrade_plan, downgrade_plan, support_ticket, logout
// metric_1=usage_events, metric_2=api_latency_ms, metric_3=retention_rate,
// metric_4=cpu_usage_pct (20-25 mapped), metric_5=mrr

const RAW_SAAS_KPIS: KPIDefinition[] = [
    { id: 'saas-001', name: 'Monthly Recurring Revenue', domain: 'SAAS', description: 'Sum of MRR signals', formulaTemplate: 'SUM(metric_5_financial)', aggregationRules: [{ function: 'SUM', column: 'metric_5_financial' }], defaultVisualizationHint: 'metric_card', requiredFields: ['metric_5_financial'], columnAliases: { metric_5_financial: ['mrr', 'monthly_revenue', 'subscription_value'] }, category: 'revenue', priority: 1, isContinuous: true, forecastable: true, sourceFiles: ['finance', 'transactions'] },
    { id: 'saas-002', name: 'MRR Trend (Daily)', domain: 'SAAS', description: 'Daily MRR for forecasting', formulaTemplate: 'SUM(metric_5_financial) GROUP BY DATE(timestamp)', aggregationRules: [{ function: 'SUM', column: 'metric_5_financial' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_5_financial', 'timestamp'], columnAliases: {}, category: 'revenue', priority: 2, isContinuous: true, forecastable: true, sourceFiles: ['finance'] },
    { id: 'saas-003', name: 'Net Retention Rate', domain: 'SAAS', description: 'Continuous retention signal', formulaTemplate: 'AVG(metric_3_rate)', aggregationRules: [{ function: 'AVG', column: 'metric_3_rate' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_3_rate'], columnAliases: { metric_3_rate: ['retention_rate', 'nrr'] }, category: 'retention', priority: 3, isContinuous: true, forecastable: true, sourceFiles: ['users', 'performance'] },
    { id: 'saas-004', name: 'Churn Rate', domain: 'SAAS', description: 'downgrade/cancel events rate', formulaTemplate: "COUNT(CASE WHEN event_style='downgrade_plan' THEN 1 END) / COUNT(DISTINCT entity_id)", aggregationRules: [{ function: 'COUNT', column: 'event_style' }], defaultVisualizationHint: 'metric_card', requiredFields: ['event_style', 'entity_id'], columnAliases: {}, category: 'retention', priority: 4, isContinuous: true, forecastable: true, sourceFiles: ['users', 'finance'] },
    { id: 'saas-005', name: 'Active Users (DAU)', domain: 'SAAS', description: 'Unique active users per day', formulaTemplate: 'COUNT(DISTINCT entity_id) GROUP BY DATE(timestamp)', aggregationRules: [{ function: 'COUNT_DISTINCT', column: 'entity_id' }], defaultVisualizationHint: 'line_chart', requiredFields: ['entity_id', 'timestamp'], columnAliases: { entity_id: ['user_id', 'account_id'] }, category: 'engagement', priority: 5, isContinuous: true, forecastable: true, sourceFiles: ['users', 'interactions'] },
    { id: 'saas-006', name: 'API Latency (P50)', domain: 'SAAS', description: 'Average API response time', formulaTemplate: 'AVG(metric_2_time_ms)', aggregationRules: [{ function: 'AVG', column: 'metric_2_time_ms' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_2_time_ms'], columnAliases: { metric_2_time_ms: ['api_latency_ms', 'response_time_ms', 'latency'] }, category: 'performance', priority: 6, isContinuous: true, forecastable: true, sourceFiles: ['system', 'performance'] },
    { id: 'saas-007', name: 'API Latency (P99)', domain: 'SAAS', description: 'Peak API response time', formulaTemplate: 'MAX(metric_2_time_ms)', aggregationRules: [{ function: 'MAX', column: 'metric_2_time_ms' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_2_time_ms'], columnAliases: { metric_2_time_ms: ['api_latency_ms', 'response_time_ms'] }, category: 'performance', priority: 7, isContinuous: true, forecastable: true, sourceFiles: ['system', 'performance'] },
    { id: 'saas-008', name: 'CPU Utilization', domain: 'SAAS', description: 'Avg CPU usage from metric_4', formulaTemplate: 'AVG(metric_4_physical)', aggregationRules: [{ function: 'AVG', column: 'metric_4_physical' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_4_physical'], columnAliases: { metric_4_physical: ['cpu_usage', 'resource_utilization'] }, category: 'performance', priority: 8, isContinuous: true, forecastable: true, sourceFiles: ['system'] },
    { id: 'saas-009', name: 'Feature Adoption Rate', domain: 'SAAS', description: 'API calls + report exports per user', formulaTemplate: "(COUNT(CASE WHEN event_style='api_call' THEN 1 END) + COUNT(CASE WHEN event_style='report_export' THEN 1 END)) / COUNT(DISTINCT entity_id)", aggregationRules: [{ function: 'COUNT', column: 'event_style' }], defaultVisualizationHint: 'metric_card', requiredFields: ['event_style', 'entity_id'], columnAliases: {}, category: 'engagement', priority: 9, isContinuous: true, forecastable: true, sourceFiles: ['interactions', 'operations'] },
    { id: 'saas-010', name: 'Upgrade Rate', domain: 'SAAS', description: 'Plan upgrade events per active user', formulaTemplate: "COUNT(CASE WHEN event_style='upgrade_plan' THEN 1 END) / COUNT(DISTINCT entity_id)", aggregationRules: [{ function: 'COUNT', column: 'event_style' }], defaultVisualizationHint: 'metric_card', requiredFields: ['event_style', 'entity_id'], columnAliases: {}, category: 'growth', priority: 10, isContinuous: true, forecastable: true, sourceFiles: ['users', 'finance'] },
    { id: 'saas-011', name: 'Support Ticket Rate', domain: 'SAAS', description: 'Support tickets per active user', formulaTemplate: "COUNT(CASE WHEN event_style='support_ticket' THEN 1 END) / COUNT(DISTINCT entity_id)", aggregationRules: [{ function: 'COUNT', column: 'event_style' }], defaultVisualizationHint: 'metric_card', requiredFields: ['event_style', 'entity_id'], columnAliases: {}, category: 'operations', priority: 11, isContinuous: true, forecastable: true, sourceFiles: ['support'] },
    { id: 'saas-012', name: 'Session Usage Depth', domain: 'SAAS', description: 'Avg usage events per session', formulaTemplate: 'AVG(metric_1_value)', aggregationRules: [{ function: 'AVG', column: 'metric_1_value' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_1_value'], columnAliases: { metric_1_value: ['usage_events', 'actions_per_session'] }, category: 'engagement', priority: 12, isContinuous: true, forecastable: true, sourceFiles: ['interactions', 'performance'] },
    { id: 'saas-013', name: 'Revenue by Segment', domain: 'SAAS', description: 'MRR by customer tier', formulaTemplate: 'SUM(metric_5_financial) GROUP BY entity_segment', aggregationRules: [{ function: 'SUM', column: 'metric_5_financial' }], defaultVisualizationHint: 'bar_chart', requiredFields: ['metric_5_financial', 'entity_segment'], columnAliases: {}, category: 'revenue', priority: 13, isContinuous: false, forecastable: false, sourceFiles: ['finance', 'users'] },
    { id: 'saas-014', name: 'System Uptime Proxy', domain: 'SAAS', description: 'Success status rate as uptime proxy', formulaTemplate: "COUNT(CASE WHEN status='Success' THEN 1 END) / COUNT(record_id)", aggregationRules: [{ function: 'COUNT', column: 'record_id' }], defaultVisualizationHint: 'line_chart', requiredFields: ['status', 'record_id'], columnAliases: {}, category: 'performance', priority: 14, isContinuous: true, forecastable: true, sourceFiles: ['system', 'operations'] },
    { id: 'saas-015', name: 'DAU/MAU Ratio', domain: 'SAAS', description: 'Stickiness metric trend', formulaTemplate: 'COUNT(DISTINCT entity_id) GROUP BY DATE(timestamp)', aggregationRules: [{ function: 'COUNT_DISTINCT', column: 'entity_id' }], defaultVisualizationHint: 'line_chart', requiredFields: ['entity_id', 'timestamp'], columnAliases: {}, category: 'engagement', priority: 15, isContinuous: true, forecastable: true, sourceFiles: ['users'] },
];
export const SAAS_KPIS = enrichKPIs(RAW_SAAS_KPIS, 'SAAS');

// ─── FINANCE ─────────────────────────────────────────────────────────────────────
// event_style: login, balance_check, transfer_init, transfer_complete, bill_pay,
//              trade_exec, loan_apply, card_swipe, atm_withdraw, support_call
// metric_1=transaction_amount, metric_2=processing_time_ms, metric_3=approval_rate,
// metric_4=risk_score, metric_5=net_revenue

const RAW_FINANCE_KPIS: KPIDefinition[] = [
    { id: 'fn-001', name: 'Total Transaction Volume', domain: 'FINANCE', description: 'Sum of all transaction amounts', formulaTemplate: 'SUM(metric_1_value)', aggregationRules: [{ function: 'SUM', column: 'metric_1_value' }], defaultVisualizationHint: 'metric_card', requiredFields: ['metric_1_value'], columnAliases: { metric_1_value: ['transaction_amount', 'transfer_amount', 'amount'] }, category: 'volume', priority: 1, isContinuous: true, forecastable: true, sourceFiles: ['transactions', 'finance'] },
    { id: 'fn-002', name: 'Transaction Count Trend', domain: 'FINANCE', description: 'Daily transaction count for forecasting', formulaTemplate: 'COUNT(record_id) GROUP BY DATE(timestamp)', aggregationRules: [{ function: 'COUNT', column: 'record_id' }], defaultVisualizationHint: 'line_chart', requiredFields: ['record_id', 'timestamp'], columnAliases: {}, category: 'volume', priority: 2, isContinuous: true, forecastable: true, sourceFiles: ['transactions'] },
    { id: 'fn-003', name: 'Net Revenue', domain: 'FINANCE', description: 'Continuous net revenue signal', formulaTemplate: 'SUM(metric_5_financial)', aggregationRules: [{ function: 'SUM', column: 'metric_5_financial' }], defaultVisualizationHint: 'metric_card', requiredFields: ['metric_5_financial'], columnAliases: { metric_5_financial: ['net_revenue', 'net_income'] }, category: 'revenue', priority: 3, isContinuous: true, forecastable: true, sourceFiles: ['finance'] },
    { id: 'fn-004', name: 'Average Processing Time', domain: 'FINANCE', description: 'Avg transaction processing latency', formulaTemplate: 'AVG(metric_2_time_ms)', aggregationRules: [{ function: 'AVG', column: 'metric_2_time_ms' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_2_time_ms'], columnAliases: { metric_2_time_ms: ['processing_time_ms', 'clearance_time_ms'] }, category: 'performance', priority: 4, isContinuous: true, forecastable: true, sourceFiles: ['performance', 'system'] },
    { id: 'fn-005', name: 'Transaction Approval Rate', domain: 'FINANCE', description: 'Continuous approval rate from metric_3', formulaTemplate: 'AVG(metric_3_rate)', aggregationRules: [{ function: 'AVG', column: 'metric_3_rate' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_3_rate'], columnAliases: { metric_3_rate: ['approval_rate', 'success_rate'] }, category: 'operations', priority: 5, isContinuous: true, forecastable: true, sourceFiles: ['transactions', 'operations'] },
    { id: 'fn-006', name: 'Average Risk Score', domain: 'FINANCE', description: 'Mean risk score per transaction', formulaTemplate: 'AVG(metric_4_physical)', aggregationRules: [{ function: 'AVG', column: 'metric_4_physical' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_4_physical'], columnAliases: { metric_4_physical: ['risk_score', 'fraud_score'] }, category: 'risk', priority: 6, isContinuous: true, forecastable: true, sourceFiles: ['operations', 'performance'] },
    { id: 'fn-007', name: 'Transfer Volume Trend', domain: 'FINANCE', description: 'Daily transfer_complete amounts', formulaTemplate: "SUM(metric_1_value) WHERE event_style='transfer_complete' GROUP BY DATE(timestamp)", aggregationRules: [{ function: 'SUM', column: 'metric_1_value' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_1_value', 'event_style', 'timestamp'], columnAliases: {}, category: 'volume', priority: 7, isContinuous: true, forecastable: true, sourceFiles: ['transactions'] },
    { id: 'fn-008', name: 'Loan Application Rate', domain: 'FINANCE', description: 'Loan applications per active user', formulaTemplate: "COUNT(CASE WHEN event_style='loan_apply' THEN 1 END) / COUNT(DISTINCT entity_id)", aggregationRules: [{ function: 'COUNT', column: 'event_style' }], defaultVisualizationHint: 'metric_card', requiredFields: ['event_style', 'entity_id'], columnAliases: {}, category: 'operations', priority: 8, isContinuous: true, forecastable: true, sourceFiles: ['operations', 'transactions'] },
    { id: 'fn-009', name: 'ATM Withdrawal Rate', domain: 'FINANCE', description: 'ATM withdrawals as ratio of events', formulaTemplate: "COUNT(CASE WHEN event_style='atm_withdraw' THEN 1 END) / COUNT(record_id)", aggregationRules: [{ function: 'COUNT', column: 'record_id' }], defaultVisualizationHint: 'metric_card', requiredFields: ['event_style', 'record_id'], columnAliases: {}, category: 'operations', priority: 9, isContinuous: true, forecastable: true, sourceFiles: ['transactions'] },
    { id: 'fn-010', name: 'Trade Execution Rate', domain: 'FINANCE', description: 'Trade events per active user per day', formulaTemplate: "COUNT(CASE WHEN event_style='trade_exec' THEN 1 END) / COUNT(DISTINCT entity_id)", aggregationRules: [{ function: 'COUNT', column: 'event_style' }], defaultVisualizationHint: 'line_chart', requiredFields: ['event_style', 'entity_id'], columnAliases: {}, category: 'volume', priority: 10, isContinuous: true, forecastable: true, sourceFiles: ['transactions'] },
    { id: 'fn-011', name: 'Net Revenue Trend', domain: 'FINANCE', description: 'Daily net revenue for forecasting', formulaTemplate: 'SUM(metric_5_financial) GROUP BY DATE(timestamp)', aggregationRules: [{ function: 'SUM', column: 'metric_5_financial' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_5_financial', 'timestamp'], columnAliases: {}, category: 'growth', priority: 11, isContinuous: true, forecastable: true, sourceFiles: ['finance'] },
    { id: 'fn-012', name: 'Revenue by Channel', domain: 'FINANCE', description: 'Net revenue by Web/Mobile/API', formulaTemplate: 'SUM(metric_5_financial) GROUP BY event_channel', aggregationRules: [{ function: 'SUM', column: 'metric_5_financial' }], defaultVisualizationHint: 'bar_chart', requiredFields: ['metric_5_financial', 'event_channel'], columnAliases: {}, category: 'revenue', priority: 12, isContinuous: false, forecastable: false, sourceFiles: ['finance', 'marketing'] },
    { id: 'fn-013', name: 'Active Users Daily', domain: 'FINANCE', description: 'Daily unique users per day', formulaTemplate: 'COUNT(DISTINCT entity_id) GROUP BY DATE(timestamp)', aggregationRules: [{ function: 'COUNT_DISTINCT', column: 'entity_id' }], defaultVisualizationHint: 'line_chart', requiredFields: ['entity_id', 'timestamp'], columnAliases: {}, category: 'customer', priority: 13, isContinuous: true, forecastable: true, sourceFiles: ['users'] },
    { id: 'fn-014', name: 'High-Risk Transaction Ratio', domain: 'FINANCE', description: 'Transactions with risk score above threshold', formulaTemplate: "COUNT(CASE WHEN metric_4_physical > 23 THEN 1 END) / COUNT(record_id)", aggregationRules: [{ function: 'COUNT', column: 'record_id' }], defaultVisualizationHint: 'metric_card', requiredFields: ['metric_4_physical', 'record_id'], columnAliases: {}, category: 'risk', priority: 14, isContinuous: true, forecastable: true, sourceFiles: ['operations', 'performance'] },
    { id: 'fn-015', name: 'Support Call Rate', domain: 'FINANCE', description: 'Support interactions per active user', formulaTemplate: "COUNT(CASE WHEN event_style='support_call' THEN 1 END) / COUNT(DISTINCT entity_id)", aggregationRules: [{ function: 'COUNT', column: 'event_style' }], defaultVisualizationHint: 'metric_card', requiredFields: ['event_style', 'entity_id'], columnAliases: {}, category: 'operations', priority: 15, isContinuous: true, forecastable: true, sourceFiles: ['support'] },
];
export const FINANCE_KPIS = enrichKPIs(RAW_FINANCE_KPIS, 'FINANCE');

// ─── HEALTHCARE ─────────────────────────────────────────────────────────────────
// event_style: appointment_book, check_in, vitals_taken, doctor_consult, lab_test,
//              prescription_issue, pharmacy_dispense, discharge, followup_call, claim_file
// metric_1=vitals_score, metric_2=wait_time_ms, metric_3=treatment_success_rate,
// metric_4=patient_temp, metric_5=claim_value

const RAW_HEALTHCARE_KPIS: KPIDefinition[] = [
    { id: 'hc-001', name: 'Total Patients Served', domain: 'HEALTHCARE', description: 'Unique patients in period', formulaTemplate: 'COUNT(DISTINCT entity_id)', aggregationRules: [{ function: 'COUNT_DISTINCT', column: 'entity_id' }], defaultVisualizationHint: 'metric_card', requiredFields: ['entity_id'], columnAliases: { entity_id: ['patient_id', 'member_id'] }, category: 'volume', priority: 1, isContinuous: true, forecastable: true, sourceFiles: ['transactions', 'users'] },
    { id: 'hc-002', name: 'Average Vitals Score', domain: 'HEALTHCARE', description: 'Continuous patient vitals signal', formulaTemplate: 'AVG(metric_1_value)', aggregationRules: [{ function: 'AVG', column: 'metric_1_value' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_1_value'], columnAliases: { metric_1_value: ['vitals_score', 'health_score', 'wellness_index'] }, category: 'quality', priority: 2, isContinuous: true, forecastable: true, sourceFiles: ['performance', 'interactions'] },
    { id: 'hc-003', name: 'Average Wait Time', domain: 'HEALTHCARE', description: 'Patient wait time in ms', formulaTemplate: 'AVG(metric_2_time_ms)', aggregationRules: [{ function: 'AVG', column: 'metric_2_time_ms' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_2_time_ms'], columnAliases: { metric_2_time_ms: ['wait_time_ms', 'queue_time_ms'] }, category: 'performance', priority: 3, isContinuous: true, forecastable: true, sourceFiles: ['operations', 'performance'] },
    { id: 'hc-004', name: 'Treatment Success Rate', domain: 'HEALTHCARE', description: 'Continuous treatment outcome signal', formulaTemplate: 'AVG(metric_3_rate)', aggregationRules: [{ function: 'AVG', column: 'metric_3_rate' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_3_rate'], columnAliases: { metric_3_rate: ['treatment_success_rate', 'outcome_rate', 'recovery_rate'] }, category: 'quality', priority: 4, isContinuous: true, forecastable: true, sourceFiles: ['performance', 'feedback'] },
    { id: 'hc-005', name: 'Average Patient Temperature', domain: 'HEALTHCARE', description: 'Mean patient temperature reading', formulaTemplate: 'AVG(metric_4_physical)', aggregationRules: [{ function: 'AVG', column: 'metric_4_physical' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_4_physical'], columnAliases: { metric_4_physical: ['patient_temp', 'body_temperature'] }, category: 'clinical', priority: 5, isContinuous: true, forecastable: true, sourceFiles: ['interactions', 'performance'] },
    { id: 'hc-006', name: 'Total Claims Value', domain: 'HEALTHCARE', description: 'Sum of all insurance claims', formulaTemplate: 'SUM(metric_5_financial)', aggregationRules: [{ function: 'SUM', column: 'metric_5_financial' }], defaultVisualizationHint: 'metric_card', requiredFields: ['metric_5_financial'], columnAliases: { metric_5_financial: ['claim_value', 'insurance_amount'] }, category: 'revenue', priority: 6, isContinuous: true, forecastable: true, sourceFiles: ['finance'] },
    { id: 'hc-007', name: 'Appointment Booking Rate', domain: 'HEALTHCARE', description: 'Daily appointment bookings', formulaTemplate: "COUNT(CASE WHEN event_style='appointment_book' THEN 1 END) GROUP BY DATE(timestamp)", aggregationRules: [{ function: 'COUNT', column: 'event_style' }], defaultVisualizationHint: 'line_chart', requiredFields: ['event_style', 'timestamp'], columnAliases: {}, category: 'volume', priority: 7, isContinuous: true, forecastable: true, sourceFiles: ['transactions', 'operations'] },
    { id: 'hc-008', name: 'Prescription Rate', domain: 'HEALTHCARE', description: 'Prescriptions per consultation', formulaTemplate: "COUNT(CASE WHEN event_style='prescription_issue' THEN 1 END) / COUNT(CASE WHEN event_style='doctor_consult' THEN 1 END)", aggregationRules: [{ function: 'COUNT', column: 'event_style' }], defaultVisualizationHint: 'metric_card', requiredFields: ['event_style'], columnAliases: {}, category: 'clinical', priority: 8, isContinuous: true, forecastable: true, sourceFiles: ['operations'] },
    { id: 'hc-009', name: 'Discharge Rate', domain: 'HEALTHCARE', description: 'Daily discharge events', formulaTemplate: "COUNT(CASE WHEN event_style='discharge' THEN 1 END) GROUP BY DATE(timestamp)", aggregationRules: [{ function: 'COUNT', column: 'event_style' }], defaultVisualizationHint: 'line_chart', requiredFields: ['event_style', 'timestamp'], columnAliases: {}, category: 'operations', priority: 9, isContinuous: true, forecastable: true, sourceFiles: ['transactions', 'operations'] },
    { id: 'hc-010', name: 'Lab Test Volume', domain: 'HEALTHCARE', description: 'Daily lab tests ordered', formulaTemplate: "COUNT(CASE WHEN event_style='lab_test' THEN 1 END) GROUP BY DATE(timestamp)", aggregationRules: [{ function: 'COUNT', column: 'event_style' }], defaultVisualizationHint: 'line_chart', requiredFields: ['event_style', 'timestamp'], columnAliases: {}, category: 'volume', priority: 10, isContinuous: true, forecastable: true, sourceFiles: ['operations'] },
    { id: 'hc-011', name: 'Follow-up Compliance Rate', domain: 'HEALTHCARE', description: 'Follow-up calls per discharge', formulaTemplate: "COUNT(CASE WHEN event_style='followup_call' THEN 1 END) / COUNT(CASE WHEN event_style='discharge' THEN 1 END)", aggregationRules: [{ function: 'COUNT', column: 'event_style' }], defaultVisualizationHint: 'metric_card', requiredFields: ['event_style'], columnAliases: {}, category: 'quality', priority: 11, isContinuous: true, forecastable: true, sourceFiles: ['support'] },
    { id: 'hc-012', name: 'Claims Trend', domain: 'HEALTHCARE', description: 'Daily claim values for forecasting', formulaTemplate: 'SUM(metric_5_financial) GROUP BY DATE(timestamp)', aggregationRules: [{ function: 'SUM', column: 'metric_5_financial' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_5_financial', 'timestamp'], columnAliases: {}, category: 'growth', priority: 12, isContinuous: true, forecastable: true, sourceFiles: ['finance'] },
    { id: 'hc-013', name: 'Regional Patient Distribution', domain: 'HEALTHCARE', description: 'Patients by region', formulaTemplate: 'COUNT(DISTINCT entity_id) GROUP BY entity_region', aggregationRules: [{ function: 'COUNT_DISTINCT', column: 'entity_id' }], defaultVisualizationHint: 'bar_chart', requiredFields: ['entity_id', 'entity_region'], columnAliases: {}, category: 'volume', priority: 13, isContinuous: false, forecastable: false, sourceFiles: ['users'] },
    { id: 'hc-014', name: 'Pharmacy Dispense Rate', domain: 'HEALTHCARE', description: 'Dispensed prescriptions ratio', formulaTemplate: "COUNT(CASE WHEN event_style='pharmacy_dispense' THEN 1 END) / COUNT(CASE WHEN event_style='prescription_issue' THEN 1 END)", aggregationRules: [{ function: 'COUNT', column: 'event_style' }], defaultVisualizationHint: 'metric_card', requiredFields: ['event_style'], columnAliases: {}, category: 'operations', priority: 14, isContinuous: true, forecastable: true, sourceFiles: ['operations'] },
    { id: 'hc-015', name: 'Max Wait Time Trend', domain: 'HEALTHCARE', description: 'Peak wait times for SLA monitoring', formulaTemplate: 'MAX(metric_2_time_ms) GROUP BY DATE(timestamp)', aggregationRules: [{ function: 'MAX', column: 'metric_2_time_ms' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_2_time_ms', 'timestamp'], columnAliases: {}, category: 'performance', priority: 15, isContinuous: true, forecastable: true, sourceFiles: ['performance', 'system'] },
];
export const HEALTHCARE_KPIS = enrichKPIs(RAW_HEALTHCARE_KPIS, 'HEALTHCARE');

// ─── MANUFACTURING ─────────────────────────────────────────────────────────────────
// event_style: shift_start, machine_start, telemetry_ping, qa_check, defect_log,
//              maintenance_req, maintenance_done, batch_complete, inventory_pull, shift_end
// metric_1=units_produced, metric_2=cycle_time_ms, metric_3=yield_rate,
// metric_4=machine_temp, metric_5=production_cost

const RAW_MANUFACTURING_KPIS: KPIDefinition[] = [
    { id: 'mf-001', name: 'Total Units Produced', domain: 'MANUFACTURING', description: 'Sum of all units produced', formulaTemplate: 'SUM(metric_1_value)', aggregationRules: [{ function: 'SUM', column: 'metric_1_value' }], defaultVisualizationHint: 'metric_card', requiredFields: ['metric_1_value'], columnAliases: { metric_1_value: ['units_produced', 'output', 'production_qty'] }, category: 'volume', priority: 1, isContinuous: true, forecastable: true, sourceFiles: ['transactions', 'operations'] },
    { id: 'mf-002', name: 'Production Output Trend', domain: 'MANUFACTURING', description: 'Daily units produced for forecasting', formulaTemplate: 'SUM(metric_1_value) GROUP BY DATE(timestamp)', aggregationRules: [{ function: 'SUM', column: 'metric_1_value' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_1_value', 'timestamp'], columnAliases: {}, category: 'volume', priority: 2, isContinuous: true, forecastable: true, sourceFiles: ['transactions', 'performance'] },
    { id: 'mf-003', name: 'Average Yield Rate', domain: 'MANUFACTURING', description: 'Continuous yield quality signal', formulaTemplate: 'AVG(metric_3_rate)', aggregationRules: [{ function: 'AVG', column: 'metric_3_rate' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_3_rate'], columnAliases: { metric_3_rate: ['yield_rate', 'quality_rate', 'pass_rate'] }, category: 'quality', priority: 3, isContinuous: true, forecastable: true, sourceFiles: ['performance', 'operations'] },
    { id: 'mf-004', name: 'Average Cycle Time', domain: 'MANUFACTURING', description: 'Mean production cycle duration in ms', formulaTemplate: 'AVG(metric_2_time_ms)', aggregationRules: [{ function: 'AVG', column: 'metric_2_time_ms' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_2_time_ms'], columnAliases: { metric_2_time_ms: ['cycle_time_ms', 'machine_time_ms', 'process_time_ms'] }, category: 'efficiency', priority: 4, isContinuous: true, forecastable: true, sourceFiles: ['performance', 'system'] },
    { id: 'mf-005', name: 'Machine Temperature', domain: 'MANUFACTURING', description: 'Continuous machine temperature monitoring', formulaTemplate: 'AVG(metric_4_physical)', aggregationRules: [{ function: 'AVG', column: 'metric_4_physical' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_4_physical'], columnAliases: { metric_4_physical: ['machine_temp', 'temperature', 'thermal_reading'] }, category: 'operations', priority: 5, isContinuous: true, forecastable: true, sourceFiles: ['system', 'performance'] },
    { id: 'mf-006', name: 'Production Cost Trend', domain: 'MANUFACTURING', description: 'Daily production cost signal', formulaTemplate: 'SUM(metric_5_financial) GROUP BY DATE(timestamp)', aggregationRules: [{ function: 'SUM', column: 'metric_5_financial' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_5_financial', 'timestamp'], columnAliases: { metric_5_financial: ['production_cost', 'unit_cost'] }, category: 'cost', priority: 6, isContinuous: true, forecastable: true, sourceFiles: ['finance'] },
    { id: 'mf-007', name: 'Defect Rate', domain: 'MANUFACTURING', description: 'defect_log events per batch', formulaTemplate: "COUNT(CASE WHEN event_style='defect_log' THEN 1 END) / COUNT(CASE WHEN event_style='batch_complete' THEN 1 END)", aggregationRules: [{ function: 'COUNT', column: 'event_style' }], defaultVisualizationHint: 'line_chart', requiredFields: ['event_style'], columnAliases: {}, category: 'quality', priority: 7, isContinuous: true, forecastable: true, sourceFiles: ['operations', 'performance'] },
    { id: 'mf-008', name: 'Maintenance Request Rate', domain: 'MANUFACTURING', description: 'Maintenance needs vs total uptime', formulaTemplate: "COUNT(CASE WHEN event_style='maintenance_req' THEN 1 END) / COUNT(CASE WHEN event_style='telemetry_ping' THEN 1 END)", aggregationRules: [{ function: 'COUNT', column: 'event_style' }], defaultVisualizationHint: 'metric_card', requiredFields: ['event_style'], columnAliases: {}, category: 'operations', priority: 8, isContinuous: true, forecastable: true, sourceFiles: ['operations', 'support'] },
    { id: 'mf-009', name: 'OEE Proxy (Yield × Throughput)', domain: 'MANUFACTURING', description: 'OEE approximation from yield and volume', formulaTemplate: 'AVG(metric_3_rate) * SUM(metric_1_value) / COUNT(record_id)', aggregationRules: [{ function: 'AVG', column: 'metric_3_rate' }, { function: 'SUM', column: 'metric_1_value' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_3_rate', 'metric_1_value', 'record_id'], columnAliases: {}, category: 'efficiency', priority: 9, isContinuous: true, forecastable: true, sourceFiles: ['performance'] },
    { id: 'mf-010', name: 'Batch Completion Rate', domain: 'MANUFACTURING', description: 'Daily completed batches', formulaTemplate: "COUNT(CASE WHEN event_style='batch_complete' THEN 1 END) GROUP BY DATE(timestamp)", aggregationRules: [{ function: 'COUNT', column: 'event_style' }], defaultVisualizationHint: 'line_chart', requiredFields: ['event_style', 'timestamp'], columnAliases: {}, category: 'volume', priority: 10, isContinuous: true, forecastable: true, sourceFiles: ['transactions', 'operations'] },
    { id: 'mf-011', name: 'Shift Efficiency', domain: 'MANUFACTURING', description: 'Units per shift window', formulaTemplate: "SUM(metric_1_value) WHERE event_style IN ('shift_start','shift_end') GROUP BY DATE(timestamp)", aggregationRules: [{ function: 'SUM', column: 'metric_1_value' }], defaultVisualizationHint: 'bar_chart', requiredFields: ['metric_1_value', 'event_style', 'timestamp'], columnAliases: {}, category: 'efficiency', priority: 11, isContinuous: true, forecastable: true, sourceFiles: ['transactions', 'operations'] },
    { id: 'mf-012', name: 'Inventory Pull Frequency', domain: 'MANUFACTURING', description: 'Raw material pulls per shift', formulaTemplate: "COUNT(CASE WHEN event_style='inventory_pull' THEN 1 END) GROUP BY DATE(timestamp)", aggregationRules: [{ function: 'COUNT', column: 'event_style' }], defaultVisualizationHint: 'line_chart', requiredFields: ['event_style', 'timestamp'], columnAliases: {}, category: 'operations', priority: 12, isContinuous: true, forecastable: true, sourceFiles: ['operations'] },
    { id: 'mf-013', name: 'Machine Utilization Rate', domain: 'MANUFACTURING', description: 'machine_start events vs shift hours', formulaTemplate: "COUNT(CASE WHEN event_style='machine_start' THEN 1 END) / COUNT(CASE WHEN event_style='shift_start' THEN 1 END)", aggregationRules: [{ function: 'COUNT', column: 'event_style' }], defaultVisualizationHint: 'metric_card', requiredFields: ['event_style'], columnAliases: {}, category: 'efficiency', priority: 13, isContinuous: true, forecastable: true, sourceFiles: ['operations', 'performance'] },
    { id: 'mf-014', name: 'QA Check Pass Rate', domain: 'MANUFACTURING', description: 'Successful QA checks per run', formulaTemplate: "COUNT(CASE WHEN event_style='qa_check' AND status='Success' THEN 1 END) / COUNT(CASE WHEN event_style='qa_check' THEN 1 END)", aggregationRules: [{ function: 'COUNT', column: 'event_style' }], defaultVisualizationHint: 'line_chart', requiredFields: ['event_style', 'status'], columnAliases: {}, category: 'quality', priority: 14, isContinuous: true, forecastable: true, sourceFiles: ['performance', 'operations'] },
    { id: 'mf-015', name: 'Peak Cycle Time', domain: 'MANUFACTURING', description: 'Max cycle time for bottleneck detection', formulaTemplate: 'MAX(metric_2_time_ms) GROUP BY DATE(timestamp)', aggregationRules: [{ function: 'MAX', column: 'metric_2_time_ms' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_2_time_ms', 'timestamp'], columnAliases: {}, category: 'efficiency', priority: 15, isContinuous: true, forecastable: true, sourceFiles: ['performance', 'system'] },
];
export const MANUFACTURING_KPIS = enrichKPIs(RAW_MANUFACTURING_KPIS, 'MANUFACTURING');

// ─── SERVICES ─────────────────────────────────────────────────────────────────────
// event_style: client_onboard, project_kickoff, timesheet_log, milestone_reach,
//              invoice_sent, payment_recv, feedback_req, feedback_recv, issue_log, issue_resolve
// metric_1=billable_hours, metric_2=response_time_ms, metric_3=sla_met_rate,
// metric_4=csat_score, metric_5=invoice_value

const RAW_SERVICES_KPIS: KPIDefinition[] = [
    { id: 'sv-001', name: 'Total Invoice Value', domain: 'SERVICES', description: 'Sum of all invoices issued', formulaTemplate: 'SUM(metric_5_financial)', aggregationRules: [{ function: 'SUM', column: 'metric_5_financial' }], defaultVisualizationHint: 'metric_card', requiredFields: ['metric_5_financial'], columnAliases: { metric_5_financial: ['invoice_value', 'billing_amount', 'revenue'] }, category: 'revenue', priority: 1, isContinuous: true, forecastable: true, sourceFiles: ['finance', 'transactions'] },
    { id: 'sv-002', name: 'Revenue Trend (Daily)', domain: 'SERVICES', description: 'Daily invoice revenue for forecasting', formulaTemplate: 'SUM(metric_5_financial) GROUP BY DATE(timestamp)', aggregationRules: [{ function: 'SUM', column: 'metric_5_financial' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_5_financial', 'timestamp'], columnAliases: {}, category: 'revenue', priority: 2, isContinuous: true, forecastable: true, sourceFiles: ['finance'] },
    { id: 'sv-003', name: 'Total Billable Hours', domain: 'SERVICES', description: 'Sum of all billable hours logged', formulaTemplate: 'SUM(metric_1_value)', aggregationRules: [{ function: 'SUM', column: 'metric_1_value' }], defaultVisualizationHint: 'metric_card', requiredFields: ['metric_1_value'], columnAliases: { metric_1_value: ['billable_hours', 'hours_logged', 'work_hours'] }, category: 'efficiency', priority: 3, isContinuous: true, forecastable: true, sourceFiles: ['operations', 'transactions'] },
    { id: 'sv-004', name: 'Average Response Time', domain: 'SERVICES', description: 'Mean SLA response time in ms', formulaTemplate: 'AVG(metric_2_time_ms)', aggregationRules: [{ function: 'AVG', column: 'metric_2_time_ms' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_2_time_ms'], columnAliases: { metric_2_time_ms: ['response_time_ms', 'sla_time_ms', 'turnaround_ms'] }, category: 'performance', priority: 4, isContinuous: true, forecastable: true, sourceFiles: ['performance', 'support'] },
    { id: 'sv-005', name: 'SLA Compliance Rate', domain: 'SERVICES', description: 'Continuous SLA met signal', formulaTemplate: 'AVG(metric_3_rate)', aggregationRules: [{ function: 'AVG', column: 'metric_3_rate' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_3_rate'], columnAliases: { metric_3_rate: ['sla_met_rate', 'on_time_rate', 'compliance_rate'] }, category: 'performance', priority: 5, isContinuous: true, forecastable: true, sourceFiles: ['performance', 'operations'] },
    { id: 'sv-006', name: 'CSAT Score', domain: 'SERVICES', description: 'Average customer satisfaction score', formulaTemplate: 'AVG(metric_4_physical)', aggregationRules: [{ function: 'AVG', column: 'metric_4_physical' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_4_physical'], columnAliases: { metric_4_physical: ['csat_score', 'satisfaction_score', 'nps_score'] }, category: 'quality', priority: 6, isContinuous: true, forecastable: true, sourceFiles: ['feedback'] },
    { id: 'sv-007', name: 'CSAT Trend', domain: 'SERVICES', description: 'Daily CSAT for forecasting', formulaTemplate: 'AVG(metric_4_physical) GROUP BY DATE(timestamp)', aggregationRules: [{ function: 'AVG', column: 'metric_4_physical' }], defaultVisualizationHint: 'line_chart', requiredFields: ['metric_4_physical', 'timestamp'], columnAliases: {}, category: 'quality', priority: 7, isContinuous: true, forecastable: true, sourceFiles: ['feedback'] },
    { id: 'sv-008', name: 'Issue Resolution Rate', domain: 'SERVICES', description: 'Resolved vs logged issues', formulaTemplate: "COUNT(CASE WHEN event_style='issue_resolve' THEN 1 END) / COUNT(CASE WHEN event_style='issue_log' THEN 1 END)", aggregationRules: [{ function: 'COUNT', column: 'event_style' }], defaultVisualizationHint: 'metric_card', requiredFields: ['event_style'], columnAliases: {}, category: 'operations', priority: 8, isContinuous: true, forecastable: true, sourceFiles: ['support', 'operations'] },
    { id: 'sv-009', name: 'Milestone Achievement Rate', domain: 'SERVICES', description: 'Milestones reached per project', formulaTemplate: "COUNT(CASE WHEN event_style='milestone_reach' THEN 1 END) / COUNT(CASE WHEN event_style='project_kickoff' THEN 1 END)", aggregationRules: [{ function: 'COUNT', column: 'event_style' }], defaultVisualizationHint: 'metric_card', requiredFields: ['event_style'], columnAliases: {}, category: 'performance', priority: 9, isContinuous: true, forecastable: true, sourceFiles: ['operations', 'transactions'] },
    { id: 'sv-010', name: 'Payment Receipt Rate', domain: 'SERVICES', description: 'Payments received vs invoices sent', formulaTemplate: "COUNT(CASE WHEN event_style='payment_recv' THEN 1 END) / COUNT(CASE WHEN event_style='invoice_sent' THEN 1 END)", aggregationRules: [{ function: 'COUNT', column: 'event_style' }], defaultVisualizationHint: 'metric_card', requiredFields: ['event_style'], columnAliases: {}, category: 'revenue', priority: 10, isContinuous: true, forecastable: true, sourceFiles: ['finance', 'transactions'] },
    { id: 'sv-011', name: 'Client Onboarding Rate', domain: 'SERVICES', description: 'New clients onboarded per day', formulaTemplate: "COUNT(CASE WHEN event_style='client_onboard' THEN 1 END) GROUP BY DATE(timestamp)", aggregationRules: [{ function: 'COUNT', column: 'event_style' }], defaultVisualizationHint: 'line_chart', requiredFields: ['event_style', 'timestamp'], columnAliases: {}, category: 'growth', priority: 11, isContinuous: true, forecastable: true, sourceFiles: ['transactions', 'marketing'] },
    { id: 'sv-012', name: 'Utilization Rate', domain: 'SERVICES', description: 'Billable hours vs total logged', formulaTemplate: "SUM(metric_1_value) WHERE event_style='timesheet_log' / SUM(metric_1_value)", aggregationRules: [{ function: 'SUM', column: 'metric_1_value' }], defaultVisualizationHint: 'metric_card', requiredFields: ['metric_1_value', 'event_style'], columnAliases: {}, category: 'efficiency', priority: 12, isContinuous: true, forecastable: true, sourceFiles: ['operations', 'users'] },
    { id: 'sv-013', name: 'Feedback Response Rate', domain: 'SERVICES', description: 'Feedback received vs requested', formulaTemplate: "COUNT(CASE WHEN event_style='feedback_recv' THEN 1 END) / COUNT(CASE WHEN event_style='feedback_req' THEN 1 END)", aggregationRules: [{ function: 'COUNT', column: 'event_style' }], defaultVisualizationHint: 'metric_card', requiredFields: ['event_style'], columnAliases: {}, category: 'quality', priority: 13, isContinuous: true, forecastable: true, sourceFiles: ['feedback'] },
    { id: 'sv-014', name: 'Active Client Count', domain: 'SERVICES', description: 'Unique clients per period', formulaTemplate: 'COUNT(DISTINCT entity_id) GROUP BY DATE(timestamp)', aggregationRules: [{ function: 'COUNT_DISTINCT', column: 'entity_id' }], defaultVisualizationHint: 'line_chart', requiredFields: ['entity_id', 'timestamp'], columnAliases: { entity_id: ['client_id', 'customer_id'] }, category: 'customer', priority: 14, isContinuous: true, forecastable: true, sourceFiles: ['users'] },
    { id: 'sv-015', name: 'Revenue by Channel', domain: 'SERVICES', description: 'Invoice value by delivery channel', formulaTemplate: 'SUM(metric_5_financial) GROUP BY event_channel', aggregationRules: [{ function: 'SUM', column: 'metric_5_financial' }], defaultVisualizationHint: 'bar_chart', requiredFields: ['metric_5_financial', 'event_channel'], columnAliases: {}, category: 'revenue', priority: 15, isContinuous: false, forecastable: false, sourceFiles: ['finance', 'marketing'] },
];
export const SERVICES_KPIS = enrichKPIs(RAW_SERVICES_KPIS, 'SERVICES');

// ─── ALL KPIS MAP ─────────────────────────────────────────────────────────────────

export const ALL_DOMAIN_KPIS: Record<DomainType, KPIDefinition[]> = {
    ECOMMERCE: ECOMMERCE_KPIS,
    EDTECH: EDTECH_KPIS,
    RETAIL: RETAIL_KPIS,
    SAAS: SAAS_KPIS,
    FINANCE: FINANCE_KPIS,
    HEALTHCARE: HEALTHCARE_KPIS,
    MANUFACTURING: MANUFACTURING_KPIS,
    SERVICES: SERVICES_KPIS,
};

export function getKPIsForDomain(domain: DomainType): KPIDefinition[] {
    return ALL_DOMAIN_KPIS[domain] || [];
}

export function getContinuousKPIs(domain: DomainType): KPIDefinition[] {
    return getKPIsForDomain(domain).filter(k => k.isContinuous);
}

export function getForecastableKPIs(domain: DomainType): KPIDefinition[] {
    return getKPIsForDomain(domain).filter(k => k.forecastable);
}

export function getKPIsBySourceFile(domain: DomainType, fileTheme: string): KPIDefinition[] {
    return getKPIsForDomain(domain).filter(k => k.sourceFiles?.includes(fileTheme));
}

// ─── Backward-Compatible Aliases ────────────────────────────────────────────────
// These keep existing consumers (section-builder, kpi-executor, scripts) compiling.

/** @deprecated Use ALL_DOMAIN_KPIS instead */
export const KPI_LIBRARY: Record<string, KPIDefinition[]> = {
    ECOMMERCE:     ECOMMERCE_KPIS,
    EDTECH:        EDTECH_KPIS,
    RETAIL:        RETAIL_KPIS,
    SAAS:          SAAS_KPIS,
    FINANCE:       FINANCE_KPIS,
    HEALTHCARE:    HEALTHCARE_KPIS,
    MANUFACTURING: MANUFACTURING_KPIS,
    SERVICES:      SERVICES_KPIS,
};

/** @deprecated Use getKPIsForDomain(domain) instead */
export function getAllKPIs(): KPIDefinition[] {
    return Object.values(ALL_DOMAIN_KPIS).flat();
}

