// KPI Library - Master definitions for all 8 domains
// Module 4 Phase 4A

import type { DomainType } from '../prisma';
import { DOMAIN_ALIASES } from './semantic-column-aliases';

export interface KPIDefinition {
    id: string;
    name: string;
    domain: DomainType;
    description: string;
    requiredFields: string[];
    formulaTemplate: string;
    aggregationRules: { function: string; column: string }[];
    defaultVisualizationHint: string;
    columnAliases: Record<string, string[]>;
    category: string;
    priority: number;
}

/**
 * Helper to enrich a list of KPIs with the latest semantic aliases for their domain.
 */
function enrichKPIs(kpis: KPIDefinition[], domain: DomainType): KPIDefinition[] {
    const domainAliases = DOMAIN_ALIASES[domain] || {};
    return kpis.map(kpi => {
        const enhancedAliases: Record<string, string[]> = { ...kpi.columnAliases };
        for (const field of kpi.requiredFields) {
            // Check if field exists in domainAliases or universal aliases
            const globalAliases = (domainAliases as any)[field] || [];
            if (globalAliases.length > 0) {
                enhancedAliases[field] = Array.from(new Set([...(enhancedAliases[field] || []), ...globalAliases]));
            }
        }
        return { ...kpi, columnAliases: enhancedAliases };
    });
}

// E-COMMERCE KPIs (20)
const RAW_ECOMMERCE_KPIS: KPIDefinition[] = [
    { id: 'ec-001', name: 'Total Revenue', domain: 'ECOMMERCE', description: 'Sum of all order values', formulaTemplate: 'SUM(revenue)', aggregationRules: [{ function: 'SUM', column: 'revenue' }], defaultVisualizationHint: 'metric_card', requiredFields: ['revenue'], columnAliases: { revenue: ['total_amount', 'order_value', 'sales', 'amount', 'price', 'order_total'] }, category: 'revenue', priority: 1 },
    { id: 'ec-002', name: 'Orders Count', domain: 'ECOMMERCE', description: 'Total number of orders', formulaTemplate: 'COUNT(order_id)', aggregationRules: [{ function: 'COUNT', column: 'order_id' }], defaultVisualizationHint: 'bar_chart', requiredFields: ['order_id'], columnAliases: { order_id: ['order_number', 'transaction_id', 'invoice_id'] }, category: 'volume', priority: 2 },
    { id: 'ec-003', name: 'Average Order Value', domain: 'ECOMMERCE', description: 'Revenue per order', formulaTemplate: 'SUM(revenue) / COUNT(order_id)', aggregationRules: [{ function: 'SUM', column: 'revenue' }, { function: 'COUNT', column: 'order_id' }], defaultVisualizationHint: 'metric_card', requiredFields: ['revenue', 'order_id'], columnAliases: { revenue: ['total_amount', 'order_value'], order_id: ['order_number'] }, category: 'revenue', priority: 3 },
    { id: 'ec-004', name: 'Conversion Rate', domain: 'ECOMMERCE', description: 'Orders / Visitors', formulaTemplate: 'COUNT(order_id) / COUNT(DISTINCT visitor_id)', aggregationRules: [{ function: 'COUNT', column: 'order_id' }, { function: 'COUNT_DISTINCT', column: 'visitor_id' }], defaultVisualizationHint: 'metric_card', requiredFields: ['order_id', 'visitor_id'], columnAliases: { visitor_id: ['session_id', 'user_id', 'customer_id'], order_id: ['order_number'] }, category: 'conversion', priority: 4 },
    { id: 'ec-005', name: 'Cart Abandonment Rate', domain: 'ECOMMERCE', description: 'Abandoned carts vs total', formulaTemplate: '(COUNT(cart_id) - COUNT(order_id)) / COUNT(cart_id)', aggregationRules: [{ function: 'COUNT', column: 'cart_id' }, { function: 'COUNT', column: 'order_id' }], defaultVisualizationHint: 'metric_card', requiredFields: ['cart_id', 'order_id'], columnAliases: { cart_id: ['basket_id', 'order_id'], order_id: ['order_number'] }, category: 'conversion', priority: 5 },
    { id: 'ec-006', name: 'Customer Lifetime Value', domain: 'ECOMMERCE', description: 'Total value per customer', formulaTemplate: 'SUM(revenue) / COUNT(DISTINCT customer_id)', aggregationRules: [{ function: 'SUM', column: 'revenue' }, { function: 'COUNT_DISTINCT', column: 'customer_id' }], defaultVisualizationHint: 'metric_card', requiredFields: ['revenue', 'customer_id'], columnAliases: { revenue: ['total_amount', 'order_value', 'sales'], customer_id: ['user_id', 'buyer_id'] }, category: 'customer', priority: 6 },
    { id: 'ec-007', name: 'Customer Acquisition Cost', domain: 'ECOMMERCE', description: 'Marketing spend per new customer', formulaTemplate: 'SUM(marketing_cost) / COUNT(DISTINCT customer_id)', aggregationRules: [{ function: 'SUM', column: 'marketing_cost' }, { function: 'COUNT_DISTINCT', column: 'customer_id' }], defaultVisualizationHint: 'metric_card', requiredFields: ['marketing_cost', 'customer_id'], columnAliases: { marketing_cost: ['ad_spend', 'acquisition_cost', 'marketing_spend'], customer_id: ['user_id', 'buyer_id'] }, category: 'marketing', priority: 7 },
    { id: 'ec-008', name: 'Gross Margin', domain: 'ECOMMERCE', description: 'Revenue minus COGS', formulaTemplate: '(SUM(revenue) - SUM(cogs)) / SUM(revenue)', aggregationRules: [{ function: 'SUM', column: 'revenue' }, { function: 'SUM', column: 'cogs' }], defaultVisualizationHint: 'metric_card', requiredFields: ['revenue', 'cogs'], columnAliases: { revenue: ['order_value'], cogs: ['cost_of_goods', 'product_cost', 'cost'] }, category: 'profitability', priority: 8 },
    { id: 'ec-009', name: 'Net Profit', domain: 'ECOMMERCE', description: 'Revenue minus all costs', formulaTemplate: 'SUM(revenue) - SUM(total_cost)', aggregationRules: [{ function: 'SUM', column: 'revenue' }, { function: 'SUM', column: 'total_cost' }], defaultVisualizationHint: 'metric_card', requiredFields: ['revenue', 'total_cost'], columnAliases: { revenue: ['order_value'], total_cost: ['expenses', 'costs', 'cost'] }, category: 'profitability', priority: 9 },
    { id: 'ec-010', name: 'Product Sales Volume', domain: 'ECOMMERCE', description: 'Units sold', formulaTemplate: 'SUM(quantity)', aggregationRules: [{ function: 'SUM', column: 'quantity' }], defaultVisualizationHint: 'bar_chart', requiredFields: ['quantity'], columnAliases: { quantity: ['qty', 'units', 'items_sold'] }, category: 'volume', priority: 10 },
    { id: 'ec-011', name: 'Return Rate', domain: 'ECOMMERCE', description: 'Returns vs orders', formulaTemplate: 'COUNT(return_id) / COUNT(order_id)', aggregationRules: [{ function: 'COUNT', column: 'return_id' }, { function: 'COUNT', column: 'order_id' }], defaultVisualizationHint: 'metric_card', requiredFields: ['return_id', 'order_id'], columnAliases: { return_id: ['refund_id', 'return_status'], order_id: ['order_number'] }, category: 'operations', priority: 11 },
    { id: 'ec-012', name: 'Refund Amount', domain: 'ECOMMERCE', description: 'Total refunds issued', formulaTemplate: 'SUM(refund_amount)', aggregationRules: [{ function: 'SUM', column: 'refund_amount' }], defaultVisualizationHint: 'metric_card', requiredFields: ['refund_amount'], columnAliases: { refund_amount: ['return_value', 'refund_value'] }, category: 'revenue', priority: 12 },
    { id: 'ec-013', name: 'Discount Impact', domain: 'ECOMMERCE', description: 'Total discounts applied', formulaTemplate: 'SUM(discount_amount)', aggregationRules: [{ function: 'SUM', column: 'discount_amount' }], defaultVisualizationHint: 'metric_card', requiredFields: ['discount_amount'], columnAliases: { discount_amount: ['promo_value', 'coupon_value'] }, category: 'revenue', priority: 13 },
    { id: 'ec-014', name: 'Revenue by Category', domain: 'ECOMMERCE', description: 'Revenue per product category', formulaTemplate: 'SUM(revenue) GROUP BY category', aggregationRules: [{ function: 'SUM', column: 'revenue' }], defaultVisualizationHint: 'bar_chart', requiredFields: ['revenue', 'category'], columnAliases: { revenue: ['order_value'], category: ['product_category', 'dept'] }, category: 'revenue', priority: 14 },
    { id: 'ec-015', name: 'Revenue by Channel', domain: 'ECOMMERCE', description: 'Revenue per sales channel', formulaTemplate: 'SUM(revenue) GROUP BY channel', aggregationRules: [{ function: 'SUM', column: 'revenue' }], defaultVisualizationHint: 'bar_chart', requiredFields: ['revenue', 'channel'], columnAliases: { revenue: ['order_value'], channel: ['source', 'platform'] }, category: 'revenue', priority: 15 },
    { id: 'ec-016', name: 'New vs Returning Customers', domain: 'ECOMMERCE', description: 'Customer type breakdown', formulaTemplate: 'COUNT(DISTINCT customer_id) GROUP BY is_new', aggregationRules: [{ function: 'COUNT_DISTINCT', column: 'customer_id' }], defaultVisualizationHint: 'bar_chart', requiredFields: ['customer_id', 'is_new'], columnAliases: { is_new: ['customer_type', 'new_customer'] }, category: 'customer', priority: 16 },
    { id: 'ec-017', name: 'Revenue Growth Rate', domain: 'ECOMMERCE', description: 'Period over period growth', formulaTemplate: '(current_revenue - prev_revenue) / prev_revenue', aggregationRules: [], defaultVisualizationHint: 'line_chart', requiredFields: ['revenue', 'date'], columnAliases: { revenue: ['order_value'], date: ['order_date', 'created_at'] }, category: 'growth', priority: 17 },
    { id: 'ec-018', name: 'Monthly Active Customers', domain: 'ECOMMERCE', description: 'Unique buyers per month', formulaTemplate: 'COUNT(DISTINCT customer_id) BY month', aggregationRules: [{ function: 'COUNT_DISTINCT', column: 'customer_id' }], defaultVisualizationHint: 'metric_card', requiredFields: ['customer_id', 'date'], columnAliases: { date: ['order_date'] }, category: 'customer', priority: 18 },
    { id: 'ec-019', name: 'Inventory Turnover', domain: 'ECOMMERCE', description: 'Stock rotation rate', formulaTemplate: 'SUM(cogs) / AVG(inventory_value)', aggregationRules: [{ function: 'SUM', column: 'cogs' }, { function: 'AVG', column: 'inventory_value' }], defaultVisualizationHint: 'metric_card', requiredFields: ['cogs', 'inventory_value'], columnAliases: { cogs: ['cost'], inventory_value: ['stock_value'] }, category: 'operations', priority: 19 },
    { id: 'ec-020', name: 'Top Selling Products', domain: 'ECOMMERCE', description: 'Best performers by revenue', formulaTemplate: 'SUM(revenue) GROUP BY product ORDER BY DESC LIMIT 10', aggregationRules: [{ function: 'SUM', column: 'revenue' }], defaultVisualizationHint: 'bar_chart', requiredFields: ['revenue', 'product'], columnAliases: { revenue: ['order_value'], product: ['product_name', 'sku'] }, category: 'product', priority: 20 },
];

export const ECOMMERCE_KPIS = enrichKPIs(RAW_ECOMMERCE_KPIS, 'ECOMMERCE');

// SAAS KPIs (20)
const RAW_SAAS_KPIS: KPIDefinition[] = [
    { id: 'saas-001', name: 'Monthly Recurring Revenue', domain: 'SAAS', description: 'Total monthly subscription revenue', formulaTemplate: 'SUM(mrr)', aggregationRules: [{ function: 'SUM', column: 'mrr' }], defaultVisualizationHint: 'metric_card', requiredFields: ['mrr'], columnAliases: { mrr: ['monthly_revenue', 'subscription_fee', 'plan_price'] }, category: 'revenue', priority: 1 },
    { id: 'saas-002', name: 'Annual Recurring Revenue', domain: 'SAAS', description: 'MRR * 12', formulaTemplate: 'SUM(mrr) * 12', aggregationRules: [{ function: 'SUM', column: 'mrr' }], defaultVisualizationHint: 'metric_card', requiredFields: ['mrr'], columnAliases: { mrr: ['arr', 'annual_revenue'] }, category: 'revenue', priority: 2 },
    { id: 'saas-003', name: 'Churn Rate', domain: 'SAAS', description: 'Lost customers / Total', formulaTemplate: 'COUNT(churned) / COUNT(customer_id)', aggregationRules: [{ function: 'COUNT', column: 'churned' }, { function: 'COUNT', column: 'customer_id' }], defaultVisualizationHint: 'metric_card', requiredFields: ['churned', 'customer_id'], columnAliases: { churned: ['cancelled', 'lost'] }, category: 'retention', priority: 3 },
    { id: 'saas-004', name: 'Net Revenue Retention', domain: 'SAAS', description: 'Expansion minus churn', formulaTemplate: '(start_mrr + expansion - churn) / start_mrr', aggregationRules: [], defaultVisualizationHint: 'metric_card', requiredFields: ['mrr', 'expansion', 'churn'], columnAliases: {}, category: 'retention', priority: 4 },
    { id: 'saas-005', name: 'Gross Revenue Retention', domain: 'SAAS', description: 'Retained revenue only', formulaTemplate: '(start_mrr - churn) / start_mrr', aggregationRules: [], defaultVisualizationHint: 'metric_card', requiredFields: ['mrr', 'churn'], columnAliases: {}, category: 'retention', priority: 5 },
    { id: 'saas-006', name: 'Customer Lifetime Value', domain: 'SAAS', description: 'ARPU / Churn Rate', formulaTemplate: 'AVG(mrr) / churn_rate', aggregationRules: [{ function: 'AVG', column: 'mrr' }], defaultVisualizationHint: 'metric_card', requiredFields: ['mrr', 'churn_rate'], columnAliases: {}, category: 'customer', priority: 6 },
    { id: 'saas-007', name: 'Customer Acquisition Cost', domain: 'SAAS', description: 'S&M spend per new customer', formulaTemplate: 'SUM(sales_marketing_cost) / COUNT(customer_id)', aggregationRules: [{ function: 'SUM', column: 'sales_marketing_cost' }, { function: 'COUNT', column: 'customer_id' }], defaultVisualizationHint: 'metric_card', requiredFields: ['sales_marketing_cost', 'customer_id'], columnAliases: { sales_marketing_cost: ['cac', 'acquisition_cost'], customer_id: ['user_id', 'buyer_id'] }, category: 'marketing', priority: 7 },
    { id: 'saas-008', name: 'Active Users', domain: 'SAAS', description: 'Users with recent activity', formulaTemplate: 'COUNT(DISTINCT user_id) WHERE last_active > threshold', aggregationRules: [{ function: 'COUNT_DISTINCT', column: 'user_id' }], defaultVisualizationHint: 'metric_card', requiredFields: ['user_id', 'last_active'], columnAliases: { last_active: ['last_login', 'activity_date'] }, category: 'engagement', priority: 8 },
    { id: 'saas-009', name: 'Trial Conversion Rate', domain: 'SAAS', description: 'Trials to paid', formulaTemplate: 'COUNT(converted) / COUNT(trials)', aggregationRules: [{ function: 'COUNT', column: 'converted' }, { function: 'COUNT', column: 'trials' }], defaultVisualizationHint: 'metric_card', requiredFields: ['converted', 'trials'], columnAliases: { trials: ['trial_started'] }, category: 'conversion', priority: 9 },
    { id: 'saas-010', name: 'Feature Usage Rate', domain: 'SAAS', description: 'Feature adoption', formulaTemplate: 'COUNT(feature_used) / COUNT(users)', aggregationRules: [{ function: 'COUNT', column: 'feature_used' }, { function: 'COUNT', column: 'users' }], defaultVisualizationHint: 'metric_card', requiredFields: ['feature_used', 'users'], columnAliases: {}, category: 'engagement', priority: 10 },
    { id: 'saas-011', name: 'Expansion Revenue', domain: 'SAAS', description: 'Upgrade/upsell revenue', formulaTemplate: 'SUM(expansion_mrr)', aggregationRules: [{ function: 'SUM', column: 'expansion_mrr' }], defaultVisualizationHint: 'metric_card', requiredFields: ['expansion_mrr'], columnAliases: { expansion_mrr: ['upsell', 'upgrade_revenue'] }, category: 'revenue', priority: 11 },
    { id: 'saas-012', name: 'Contraction Revenue', domain: 'SAAS', description: 'Downgrade revenue loss', formulaTemplate: 'SUM(contraction_mrr)', aggregationRules: [{ function: 'SUM', column: 'contraction_mrr' }], defaultVisualizationHint: 'metric_card', requiredFields: ['contraction_mrr'], columnAliases: { contraction_mrr: ['downgrade'] }, category: 'revenue', priority: 12 },
    { id: 'saas-013', name: 'Average Revenue Per User', domain: 'SAAS', description: 'MRR / Users', formulaTemplate: 'SUM(mrr) / COUNT(DISTINCT user_id)', aggregationRules: [{ function: 'SUM', column: 'mrr' }, { function: 'COUNT_DISTINCT', column: 'user_id' }], defaultVisualizationHint: 'metric_card', requiredFields: ['mrr', 'user_id'], columnAliases: {}, category: 'revenue', priority: 13 },
    { id: 'saas-014', name: 'Renewal Rate', domain: 'SAAS', description: 'Renewals / Expiring', formulaTemplate: 'COUNT(renewed) / COUNT(expiring)', aggregationRules: [{ function: 'COUNT', column: 'renewed' }, { function: 'COUNT', column: 'expiring' }], defaultVisualizationHint: 'metric_card', requiredFields: ['renewed', 'expiring'], columnAliases: {}, category: 'retention', priority: 14 },
    { id: 'saas-015', name: 'Billing Success Rate', domain: 'SAAS', description: 'Successful charges', formulaTemplate: 'COUNT(successful_charge) / COUNT(charge_attempts)', aggregationRules: [{ function: 'COUNT', column: 'successful_charge' }, { function: 'COUNT', column: 'charge_attempts' }], defaultVisualizationHint: 'metric_card', requiredFields: ['successful_charge', 'charge_attempts'], columnAliases: {}, category: 'operations', priority: 15 },
    { id: 'saas-016', name: 'Failed Payments', domain: 'SAAS', description: 'Failed billing attempts', formulaTemplate: 'COUNT(failed_payment)', aggregationRules: [{ function: 'COUNT', column: 'failed_payment' }], defaultVisualizationHint: 'metric_card', requiredFields: ['failed_payment'], columnAliases: { failed_payment: ['payment_failed', 'billing_error'] }, category: 'operations', priority: 16 },
    { id: 'saas-017', name: 'Monthly New Signups', domain: 'SAAS', description: 'New registrations', formulaTemplate: 'COUNT(signup_id) BY month', aggregationRules: [{ function: 'COUNT', column: 'signup_id' }], defaultVisualizationHint: 'line_chart', requiredFields: ['signup_id', 'signup_date'], columnAliases: { signup_id: ['registration_id'] }, category: 'growth', priority: 17 },
    { id: 'saas-018', name: 'Revenue Growth Rate', domain: 'SAAS', description: 'MRR growth MoM', formulaTemplate: '(current_mrr - prev_mrr) / prev_mrr', aggregationRules: [], defaultVisualizationHint: 'line_chart', requiredFields: ['mrr', 'date'], columnAliases: {}, category: 'growth', priority: 18 },
    { id: 'saas-019', name: 'Customer Count', domain: 'SAAS', description: 'Total paying customers', formulaTemplate: 'COUNT(DISTINCT customer_id) WHERE status=active', aggregationRules: [{ function: 'COUNT_DISTINCT', column: 'customer_id' }], defaultVisualizationHint: 'metric_card', requiredFields: ['customer_id', 'status'], columnAliases: {}, category: 'customer', priority: 19 },
    { id: 'saas-020', name: 'Usage per User', domain: 'SAAS', description: 'Average platform usage', formulaTemplate: 'SUM(usage_minutes) / COUNT(DISTINCT user_id)', aggregationRules: [{ function: 'SUM', column: 'usage_minutes' }, { function: 'COUNT_DISTINCT', column: 'user_id' }], defaultVisualizationHint: 'metric_card', requiredFields: ['usage_minutes', 'user_id'], columnAliases: { usage_minutes: ['session_time', 'time_spent'] }, category: 'engagement', priority: 20 },
];

export const SAAS_KPIS = enrichKPIs(RAW_SAAS_KPIS, 'SAAS');

// Remaining domains follow same pattern
const RAW_EDTECH_KPIS: KPIDefinition[] = [
    { id: 'ed-001', name: 'Total Enrollments', domain: 'EDTECH', description: 'Total course enrollments', formulaTemplate: 'COUNT(enrollment_id)', aggregationRules: [{ function: 'COUNT', column: 'enrollment_id' }], defaultVisualizationHint: 'bar_chart', requiredFields: ['enrollment_id'], columnAliases: { enrollment_id: ['registration_id', 'signup_id'] }, category: 'volume', priority: 1 },
    { id: 'ed-002', name: 'Course Completion Rate', domain: 'EDTECH', description: 'Completed / Enrolled', formulaTemplate: 'COUNT(completed) / COUNT(enrolled)', aggregationRules: [{ function: 'COUNT', column: 'completed' }, { function: 'COUNT', column: 'enrolled' }], defaultVisualizationHint: 'metric_card', requiredFields: ['completed', 'enrolled'], columnAliases: {}, category: 'engagement', priority: 2 },
    { id: 'ed-003', name: 'Student Engagement Rate', domain: 'EDTECH', description: 'Active learners ratio', formulaTemplate: 'COUNT(active_students) / COUNT(total_students)', aggregationRules: [{ function: 'COUNT', column: 'active_students' }, { function: 'COUNT', column: 'total_students' }], defaultVisualizationHint: 'metric_card', requiredFields: ['active_students', 'total_students'], columnAliases: {}, category: 'engagement', priority: 3 },
    { id: 'ed-004', name: 'Dropout Rate', domain: 'EDTECH', description: 'Students who left', formulaTemplate: 'COUNT(dropped) / COUNT(enrolled)', aggregationRules: [{ function: 'COUNT', column: 'dropped' }, { function: 'COUNT', column: 'enrolled' }], defaultVisualizationHint: 'metric_card', requiredFields: ['dropped', 'enrolled'], columnAliases: { dropped: ['withdrawn', 'cancelled'] }, category: 'retention', priority: 4 },
    { id: 'ed-005', name: 'Average Grade', domain: 'EDTECH', description: 'Mean student score', formulaTemplate: 'AVG(grade)', aggregationRules: [{ function: 'AVG', column: 'grade' }], defaultVisualizationHint: 'metric_card', requiredFields: ['grade'], columnAliases: { grade: ['score', 'marks', 'percentage'] }, category: 'performance', priority: 5 },
    { id: 'ed-006', name: 'Active Learners', domain: 'EDTECH', description: 'Currently active students', formulaTemplate: 'COUNT(DISTINCT student_id) WHERE last_active > threshold', aggregationRules: [{ function: 'COUNT_DISTINCT', column: 'student_id' }], defaultVisualizationHint: 'metric_card', requiredFields: ['student_id', 'last_active'], columnAliases: {}, category: 'engagement', priority: 6 },
    { id: 'ed-007', name: 'Revenue per Course', domain: 'EDTECH', description: 'Average course revenue', formulaTemplate: 'SUM(revenue) / COUNT(DISTINCT course_id)', aggregationRules: [{ function: 'SUM', column: 'revenue' }, { function: 'COUNT_DISTINCT', column: 'course_id' }], defaultVisualizationHint: 'metric_card', requiredFields: ['revenue', 'course_id'], columnAliases: {}, category: 'revenue', priority: 7 },
    { id: 'ed-008', name: 'Certification Rate', domain: 'EDTECH', description: 'Certified / Completed', formulaTemplate: 'COUNT(certified) / COUNT(completed)', aggregationRules: [{ function: 'COUNT', column: 'certified' }, { function: 'COUNT', column: 'completed' }], defaultVisualizationHint: 'metric_card', requiredFields: ['certified', 'completed'], columnAliases: {}, category: 'performance', priority: 8 },
    { id: 'ed-009', name: 'Quiz Pass Rate', domain: 'EDTECH', description: 'Quizzes passed', formulaTemplate: 'COUNT(passed) / COUNT(attempted)', aggregationRules: [{ function: 'COUNT', column: 'passed' }, { function: 'COUNT', column: 'attempted' }], defaultVisualizationHint: 'metric_card', requiredFields: ['passed', 'attempted'], columnAliases: {}, category: 'performance', priority: 9 },
    { id: 'ed-010', name: 'Student Retention Rate', domain: 'EDTECH', description: 'Returning students', formulaTemplate: 'COUNT(returning) / COUNT(previous_enrolled)', aggregationRules: [{ function: 'COUNT', column: 'returning' }, { function: 'COUNT', column: 'previous_enrolled' }], defaultVisualizationHint: 'metric_card', requiredFields: ['returning', 'previous_enrolled'], columnAliases: {}, category: 'retention', priority: 10 },
];

export const EDTECH_KPIS = enrichKPIs(RAW_EDTECH_KPIS, 'EDTECH');

const RAW_RETAIL_KPIS: KPIDefinition[] = [
    { id: 'rt-001', name: 'Total Sales', domain: 'RETAIL', description: 'Sum of all sales', formulaTemplate: 'SUM(sales)', aggregationRules: [{ function: 'SUM', column: 'sales' }], defaultVisualizationHint: 'metric_card', requiredFields: ['sales'], columnAliases: { sales: ['revenue', 'amount', 'total', 'total_sales', 'line_total'] }, category: 'revenue', priority: 1 },
    { id: 'rt-002', name: 'Sales Growth', domain: 'RETAIL', description: 'Period over period', formulaTemplate: '(current - previous) / previous', aggregationRules: [], defaultVisualizationHint: 'line_chart', requiredFields: ['sales', 'date'], columnAliases: {}, category: 'growth', priority: 2 },
    { id: 'rt-003', name: 'Inventory Turnover', domain: 'RETAIL', description: 'Stock rotation', formulaTemplate: 'SUM(cogs) / AVG(inventory)', aggregationRules: [{ function: 'SUM', column: 'cogs' }, { function: 'AVG', column: 'inventory' }], defaultVisualizationHint: 'metric_card', requiredFields: ['cogs', 'inventory'], columnAliases: { inventory: ['stock', 'stock_value', 'stock_qty'] }, category: 'operations', priority: 3 },
    { id: 'rt-004', name: 'Stock Level', domain: 'RETAIL', description: 'Current inventory', formulaTemplate: 'SUM(quantity_on_hand)', aggregationRules: [{ function: 'SUM', column: 'quantity_on_hand' }], defaultVisualizationHint: 'metric_card', requiredFields: ['quantity_on_hand'], columnAliases: { quantity_on_hand: ['stock_qty', 'inventory_qty', 'quantity'] }, category: 'operations', priority: 4 },
    { id: 'rt-005', name: 'Gross Margin', domain: 'RETAIL', description: 'Revenue minus COGS', formulaTemplate: '(SUM(sales) - SUM(cogs)) / SUM(sales)', aggregationRules: [{ function: 'SUM', column: 'sales' }, { function: 'SUM', column: 'cogs' }], defaultVisualizationHint: 'metric_card', requiredFields: ['sales', 'cogs'], columnAliases: {}, category: 'profitability', priority: 5 },
    { id: 'rt-006', name: 'Average Basket Size', domain: 'RETAIL', description: 'Items per transaction', formulaTemplate: 'SUM(items) / COUNT(transaction_id)', aggregationRules: [{ function: 'SUM', column: 'items' }, { function: 'COUNT', column: 'transaction_id' }], defaultVisualizationHint: 'bar_chart', requiredFields: ['items', 'transaction_id'], columnAliases: { items: ['quantity', 'qty'], transaction_id: ['order_id', 'bill_no'] }, category: 'volume', priority: 6 },
    { id: 'rt-007', name: 'Sales per Store', domain: 'RETAIL', description: 'Revenue by location', formulaTemplate: 'SUM(sales) GROUP BY store_id', aggregationRules: [{ function: 'SUM', column: 'sales' }], defaultVisualizationHint: 'bar_chart', requiredFields: ['sales', 'store_id'], columnAliases: { store_id: ['outlet', 'location', 'branch_id'] }, category: 'revenue', priority: 7 },
    { id: 'rt-008', name: 'Footfall Conversion', domain: 'RETAIL', description: 'Buyers / Visitors', formulaTemplate: 'COUNT(transaction_id) / COUNT(visitors)', aggregationRules: [{ function: 'COUNT', column: 'transaction_id' }, { function: 'COUNT', column: 'visitors' }], defaultVisualizationHint: 'metric_card', requiredFields: ['transaction_id', 'visitors'], columnAliases: { visitors: ['footfall'] }, category: 'conversion', priority: 8 },
    { id: 'rt-009', name: 'Shrinkage Rate', domain: 'RETAIL', description: 'Inventory loss', formulaTemplate: 'SUM(shrinkage) / SUM(inventory)', aggregationRules: [{ function: 'SUM', column: 'shrinkage' }, { function: 'SUM', column: 'inventory' }], defaultVisualizationHint: 'metric_card', requiredFields: ['shrinkage', 'inventory'], columnAliases: { shrinkage: ['loss', 'theft'], inventory: ['stock'] }, category: 'operations', priority: 9 },
    { id: 'rt-010', name: 'Sell-through Rate', domain: 'RETAIL', description: 'Sold vs received', formulaTemplate: 'SUM(sold) / SUM(received)', aggregationRules: [{ function: 'SUM', column: 'sold' }, { function: 'SUM', column: 'received' }], defaultVisualizationHint: 'metric_card', requiredFields: ['sold', 'received'], columnAliases: { sold: ['sold_units'], received: ['received_units'] }, category: 'operations', priority: 10 },
    { id: 'rt-011', name: 'Average Transaction Value', domain: 'RETAIL', description: 'Revenue per transaction', formulaTemplate: 'SUM(sales) / COUNT(transaction_id)', aggregationRules: [{ function: 'SUM', column: 'sales' }, { function: 'COUNT', column: 'transaction_id' }], defaultVisualizationHint: 'metric_card', requiredFields: ['sales', 'transaction_id'], columnAliases: { sales: ['total_sales'], transaction_id: ['order_id'] }, category: 'revenue', priority: 11 },
    { id: 'rt-012', name: 'Revenue per Visitor', domain: 'RETAIL', description: 'Revenue by footfall', formulaTemplate: 'SUM(sales) / COUNT(visitors)', aggregationRules: [{ function: 'SUM', column: 'sales' }, { function: 'COUNT', column: 'visitors' }], defaultVisualizationHint: 'metric_card', requiredFields: ['sales', 'visitors'], columnAliases: {}, category: 'revenue', priority: 12 },
    { id: 'rt-013', name: 'Active SKU Count', domain: 'RETAIL', description: 'Number of unique products sold', formulaTemplate: 'COUNT(DISTINCT product_id)', aggregationRules: [{ function: 'COUNT_DISTINCT', column: 'product_id' }], defaultVisualizationHint: 'bar_chart', requiredFields: ['product_id'], columnAliases: { product_id: ['sku', 'item_id'] }, category: 'product', priority: 13 },
    { id: 'rt-014', name: 'Inventory Value', domain: 'RETAIL', description: 'Total value of stock', formulaTemplate: 'SUM(inventory * cost)', aggregationRules: [{ function: 'SUM', column: 'inventory' }, { function: 'SUM', column: 'cost' }], defaultVisualizationHint: 'metric_card', requiredFields: ['inventory', 'cost'], columnAliases: {}, category: 'operations', priority: 14 },
    { id: 'rt-015', name: 'Top Categories by Revenue', domain: 'RETAIL', description: 'Best performing segments', formulaTemplate: 'SUM(sales) GROUP BY category', aggregationRules: [{ function: 'SUM', column: 'sales' }], defaultVisualizationHint: 'pie_chart', requiredFields: ['sales', 'category'], columnAliases: { category: ['product_category', 'dept'] }, category: 'product', priority: 15 },
];

export const RETAIL_KPIS = enrichKPIs(RAW_RETAIL_KPIS, 'RETAIL');

const RAW_SERVICES_KPIS: KPIDefinition[] = [
    { id: 'sv-001', name: 'Total Revenue', domain: 'SERVICES', description: 'Sum of billings', formulaTemplate: 'SUM(revenue)', aggregationRules: [{ function: 'SUM', column: 'revenue' }], defaultVisualizationHint: 'metric_card', requiredFields: ['revenue'], columnAliases: { revenue: ['billing', 'invoice_amount'] }, category: 'revenue', priority: 1 },
    { id: 'sv-002', name: 'Billable Utilization Rate', domain: 'SERVICES', description: 'Billable / Total hours', formulaTemplate: 'SUM(billable_hours) / SUM(total_hours)', aggregationRules: [{ function: 'SUM', column: 'billable_hours' }, { function: 'SUM', column: 'total_hours' }], defaultVisualizationHint: 'metric_card', requiredFields: ['billable_hours', 'total_hours'], columnAliases: {}, category: 'efficiency', priority: 2 },
    { id: 'sv-003', name: 'Average Billing Rate', domain: 'SERVICES', description: 'Revenue per hour', formulaTemplate: 'SUM(revenue) / SUM(billable_hours)', aggregationRules: [{ function: 'SUM', column: 'revenue' }, { function: 'SUM', column: 'billable_hours' }], defaultVisualizationHint: 'metric_card', requiredFields: ['revenue', 'billable_hours'], columnAliases: {}, category: 'revenue', priority: 3 },
    { id: 'sv-004', name: 'Project Profitability', domain: 'SERVICES', description: 'Revenue minus cost', formulaTemplate: 'SUM(revenue) - SUM(project_cost)', aggregationRules: [{ function: 'SUM', column: 'revenue' }, { function: 'SUM', column: 'project_cost' }], defaultVisualizationHint: 'metric_card', requiredFields: ['revenue', 'project_cost'], columnAliases: {}, category: 'profitability', priority: 4 },
    { id: 'sv-005', name: 'Client Retention Rate', domain: 'SERVICES', description: 'Returning clients', formulaTemplate: 'COUNT(returning_clients) / COUNT(total_clients)', aggregationRules: [{ function: 'COUNT', column: 'returning_clients' }, { function: 'COUNT', column: 'total_clients' }], defaultVisualizationHint: 'metric_card', requiredFields: ['returning_clients', 'total_clients'], columnAliases: {}, category: 'retention', priority: 5 },
    { id: 'sv-006', name: 'Revenue per Client', domain: 'SERVICES', description: 'Avg client value', formulaTemplate: 'SUM(revenue) / COUNT(DISTINCT client_id)', aggregationRules: [{ function: 'SUM', column: 'revenue' }, { function: 'COUNT_DISTINCT', column: 'client_id' }], defaultVisualizationHint: 'metric_card', requiredFields: ['revenue', 'client_id'], columnAliases: {}, category: 'revenue', priority: 6 },
    { id: 'sv-007', name: 'Active Projects', domain: 'SERVICES', description: 'Ongoing work', formulaTemplate: 'COUNT(project_id) WHERE status=active', aggregationRules: [{ function: 'COUNT', column: 'project_id' }], defaultVisualizationHint: 'bar_chart', requiredFields: ['project_id', 'status'], columnAliases: {}, category: 'volume', priority: 7 },
    { id: 'sv-008', name: 'Overdue Invoices', domain: 'SERVICES', description: 'Late payments', formulaTemplate: 'COUNT(invoice_id) WHERE due_date < today AND paid=false', aggregationRules: [{ function: 'COUNT', column: 'invoice_id' }], defaultVisualizationHint: 'metric_card', requiredFields: ['invoice_id', 'due_date', 'paid'], columnAliases: {}, category: 'operations', priority: 8 },
    { id: 'sv-009', name: 'Employee Utilization', domain: 'SERVICES', description: 'Staff productivity', formulaTemplate: 'SUM(hours_worked) / SUM(available_hours)', aggregationRules: [{ function: 'SUM', column: 'hours_worked' }, { function: 'SUM', column: 'available_hours' }], defaultVisualizationHint: 'metric_card', requiredFields: ['hours_worked', 'available_hours'], columnAliases: {}, category: 'efficiency', priority: 9 },
    { id: 'sv-010', name: 'Delivery Timeliness', domain: 'SERVICES', description: 'On-time deliveries', formulaTemplate: 'COUNT(on_time) / COUNT(total_deliveries)', aggregationRules: [{ function: 'COUNT', column: 'on_time' }, { function: 'COUNT', column: 'total_deliveries' }], defaultVisualizationHint: 'metric_card', requiredFields: ['on_time', 'total_deliveries'], columnAliases: {}, category: 'performance', priority: 10 },
];

export const SERVICES_KPIS = enrichKPIs(RAW_SERVICES_KPIS, 'SERVICES');

const RAW_MANUFACTURING_KPIS: KPIDefinition[] = [
    { id: 'mf-001', name: 'Production Output', domain: 'MANUFACTURING', description: 'Units produced', formulaTemplate: 'SUM(units_produced)', aggregationRules: [{ function: 'SUM', column: 'units_produced' }], defaultVisualizationHint: 'bar_chart', requiredFields: ['units_produced'], columnAliases: { units_produced: ['output', 'production_qty'] }, category: 'volume', priority: 1 },
    { id: 'mf-002', name: 'Yield Rate', domain: 'MANUFACTURING', description: 'Good units ratio', formulaTemplate: 'SUM(good_units) / SUM(total_units)', aggregationRules: [{ function: 'SUM', column: 'good_units' }, { function: 'SUM', column: 'total_units' }], defaultVisualizationHint: 'metric_card', requiredFields: ['good_units', 'total_units'], columnAliases: {}, category: 'quality', priority: 2 },
    { id: 'mf-003', name: 'Defect Rate', domain: 'MANUFACTURING', description: 'Defective ratio', formulaTemplate: 'SUM(defects) / SUM(total_units)', aggregationRules: [{ function: 'SUM', column: 'defects' }, { function: 'SUM', column: 'total_units' }], defaultVisualizationHint: 'metric_card', requiredFields: ['defects', 'total_units'], columnAliases: { defects: ['rejects', 'failures'] }, category: 'quality', priority: 3 },
    { id: 'mf-004', name: 'Overall Equipment Effectiveness', domain: 'MANUFACTURING', description: 'OEE metric', formulaTemplate: 'availability * performance * quality', aggregationRules: [], defaultVisualizationHint: 'metric_card', requiredFields: ['availability', 'performance', 'quality'], columnAliases: {}, category: 'efficiency', priority: 4 },
    { id: 'mf-005', name: 'Downtime', domain: 'MANUFACTURING', description: 'Non-productive time', formulaTemplate: 'SUM(downtime_hours)', aggregationRules: [{ function: 'SUM', column: 'downtime_hours' }], defaultVisualizationHint: 'metric_card', requiredFields: ['downtime_hours'], columnAliases: { downtime_hours: ['machine_stop', 'idle_time'] }, category: 'operations', priority: 5 },
    { id: 'mf-006', name: 'Cost per Unit', domain: 'MANUFACTURING', description: 'Production cost', formulaTemplate: 'SUM(total_cost) / SUM(units_produced)', aggregationRules: [{ function: 'SUM', column: 'total_cost' }, { function: 'SUM', column: 'units_produced' }], defaultVisualizationHint: 'metric_card', requiredFields: ['total_cost', 'units_produced'], columnAliases: {}, category: 'cost', priority: 6 },
    { id: 'mf-007', name: 'Machine Utilization', domain: 'MANUFACTURING', description: 'Running vs available', formulaTemplate: 'SUM(running_time) / SUM(available_time)', aggregationRules: [{ function: 'SUM', column: 'running_time' }, { function: 'SUM', column: 'available_time' }], defaultVisualizationHint: 'metric_card', requiredFields: ['running_time', 'available_time'], columnAliases: {}, category: 'efficiency', priority: 7 },
    { id: 'mf-008', name: 'Throughput', domain: 'MANUFACTURING', description: 'Output rate', formulaTemplate: 'SUM(units_produced) / time_period', aggregationRules: [{ function: 'SUM', column: 'units_produced' }], defaultVisualizationHint: 'bar_chart', requiredFields: ['units_produced', 'time_period'], columnAliases: {}, category: 'volume', priority: 8 },
    { id: 'mf-009', name: 'Scrap Rate', domain: 'MANUFACTURING', description: 'Wasted material', formulaTemplate: 'SUM(scrap) / SUM(material_used)', aggregationRules: [{ function: 'SUM', column: 'scrap' }, { function: 'SUM', column: 'material_used' }], defaultVisualizationHint: 'metric_card', requiredFields: ['scrap', 'material_used'], columnAliases: { scrap: ['waste'] }, category: 'quality', priority: 9 },
    { id: 'mf-010', name: 'Lead Time', domain: 'MANUFACTURING', description: 'Order to delivery', formulaTemplate: 'AVG(delivery_date - order_date)', aggregationRules: [], defaultVisualizationHint: 'metric_card', requiredFields: ['delivery_date', 'order_date'], columnAliases: {}, category: 'operations', priority: 10 },
];

export const MANUFACTURING_KPIS = enrichKPIs(RAW_MANUFACTURING_KPIS, 'MANUFACTURING');

const RAW_HEALTHCARE_KPIS: KPIDefinition[] = [
    { id: 'hc-001', name: 'Patient Count', domain: 'HEALTHCARE', description: 'Total patients', formulaTemplate: 'COUNT(DISTINCT patient_id)', aggregationRules: [{ function: 'COUNT_DISTINCT', column: 'patient_id' }], defaultVisualizationHint: 'bar_chart', requiredFields: ['patient_id'], columnAliases: { patient_id: ['member_id', 'beneficiary_id'] }, category: 'volume', priority: 1 },
    { id: 'hc-002', name: 'Appointment No-show Rate', domain: 'HEALTHCARE', description: 'Missed appointments', formulaTemplate: 'COUNT(no_show) / COUNT(appointment_id)', aggregationRules: [{ function: 'COUNT', column: 'no_show' }, { function: 'COUNT', column: 'appointment_id' }], defaultVisualizationHint: 'metric_card', requiredFields: ['no_show', 'appointment_id'], columnAliases: {}, category: 'operations', priority: 2 },
    { id: 'hc-003', name: 'Bed Occupancy Rate', domain: 'HEALTHCARE', description: 'Beds in use', formulaTemplate: 'SUM(occupied_beds) / SUM(total_beds)', aggregationRules: [{ function: 'SUM', column: 'occupied_beds' }, { function: 'SUM', column: 'total_beds' }], defaultVisualizationHint: 'metric_card', requiredFields: ['occupied_beds', 'total_beds'], columnAliases: {}, category: 'capacity', priority: 3 },
    { id: 'hc-004', name: 'Average Length of Stay', domain: 'HEALTHCARE', description: 'Days per admission', formulaTemplate: 'AVG(discharge_date - admission_date)', aggregationRules: [], defaultVisualizationHint: 'metric_card', requiredFields: ['discharge_date', 'admission_date'], columnAliases: {}, category: 'operations', priority: 4 },
    { id: 'hc-005', name: 'Readmission Rate', domain: 'HEALTHCARE', description: 'Return admissions', formulaTemplate: 'COUNT(readmission) / COUNT(discharge)', aggregationRules: [{ function: 'COUNT', column: 'readmission' }, { function: 'COUNT', column: 'discharge' }], defaultVisualizationHint: 'metric_card', requiredFields: ['readmission', 'discharge'], columnAliases: {}, category: 'quality', priority: 5 },
    { id: 'hc-006', name: 'Revenue per Patient', domain: 'HEALTHCARE', description: 'Avg patient value', formulaTemplate: 'SUM(revenue) / COUNT(DISTINCT patient_id)', aggregationRules: [{ function: 'SUM', column: 'revenue' }, { function: 'COUNT_DISTINCT', column: 'patient_id' }], defaultVisualizationHint: 'metric_card', requiredFields: ['revenue', 'patient_id'], columnAliases: {}, category: 'revenue', priority: 6 },
    { id: 'hc-007', name: 'Claim Approval Rate', domain: 'HEALTHCARE', description: 'Approved claims', formulaTemplate: 'COUNT(approved) / COUNT(submitted)', aggregationRules: [{ function: 'COUNT', column: 'approved' }, { function: 'COUNT', column: 'submitted' }], defaultVisualizationHint: 'metric_card', requiredFields: ['approved', 'submitted'], columnAliases: {}, category: 'operations', priority: 7 },
    { id: 'hc-008', name: 'Doctor Utilization', domain: 'HEALTHCARE', description: 'Physician productivity', formulaTemplate: 'SUM(patient_hours) / SUM(available_hours)', aggregationRules: [{ function: 'SUM', column: 'patient_hours' }, { function: 'SUM', column: 'available_hours' }], defaultVisualizationHint: 'metric_card', requiredFields: ['patient_hours', 'available_hours'], columnAliases: {}, category: 'efficiency', priority: 8 },
    { id: 'hc-009', name: 'Treatment Success Rate', domain: 'HEALTHCARE', description: 'Positive outcomes', formulaTemplate: 'COUNT(successful) / COUNT(treated)', aggregationRules: [{ function: 'COUNT', column: 'successful' }, { function: 'COUNT', column: 'treated' }], defaultVisualizationHint: 'metric_card', requiredFields: ['successful', 'treated'], columnAliases: {}, category: 'quality', priority: 9 },
    { id: 'hc-010', name: 'Cost per Treatment', domain: 'HEALTHCARE', description: 'Treatment economics', formulaTemplate: 'SUM(cost) / COUNT(treatment_id)', aggregationRules: [{ function: 'SUM', column: 'cost' }, { function: 'COUNT', column: 'treatment_id' }], defaultVisualizationHint: 'metric_card', requiredFields: ['cost', 'treatment_id'], columnAliases: {}, category: 'cost', priority: 10 },
];

export const HEALTHCARE_KPIS = enrichKPIs(RAW_HEALTHCARE_KPIS, 'HEALTHCARE');

const RAW_FINANCE_KPIS: KPIDefinition[] = [
    { id: 'fn-001', name: 'Total Transactions', domain: 'FINANCE', description: 'Transaction count', formulaTemplate: 'COUNT(transaction_id)', aggregationRules: [{ function: 'COUNT', column: 'transaction_id' }], defaultVisualizationHint: 'bar_chart', requiredFields: ['transaction_id'], columnAliases: { transaction_id: ['txn_id', 'payment_id'] }, category: 'volume', priority: 1 },
    { id: 'fn-002', name: 'Net Profit', domain: 'FINANCE', description: 'Revenue minus expenses', formulaTemplate: 'SUM(revenue) - SUM(expenses)', aggregationRules: [{ function: 'SUM', column: 'revenue' }, { function: 'SUM', column: 'expenses' }], defaultVisualizationHint: 'metric_card', requiredFields: ['revenue', 'expenses'], columnAliases: {}, category: 'profitability', priority: 2 },
    { id: 'fn-003', name: 'Cash Flow', domain: 'FINANCE', description: 'Net cash movement', formulaTemplate: 'SUM(inflow) - SUM(outflow)', aggregationRules: [{ function: 'SUM', column: 'inflow' }, { function: 'SUM', column: 'outflow' }], defaultVisualizationHint: 'metric_card', requiredFields: ['inflow', 'outflow'], columnAliases: { inflow: ['receipts'], outflow: ['payments'] }, category: 'liquidity', priority: 3 },
    { id: 'fn-004', name: 'Loan Default Rate', domain: 'FINANCE', description: 'Defaulted loans', formulaTemplate: 'COUNT(defaulted) / COUNT(loans)', aggregationRules: [{ function: 'COUNT', column: 'defaulted' }, { function: 'COUNT', column: 'loans' }], defaultVisualizationHint: 'metric_card', requiredFields: ['defaulted', 'loans'], columnAliases: {}, category: 'risk', priority: 4 },
    { id: 'fn-005', name: 'Return on Assets', domain: 'FINANCE', description: 'ROA metric', formulaTemplate: 'SUM(net_income) / AVG(total_assets)', aggregationRules: [{ function: 'SUM', column: 'net_income' }, { function: 'AVG', column: 'total_assets' }], defaultVisualizationHint: 'metric_card', requiredFields: ['net_income', 'total_assets'], columnAliases: {}, category: 'performance', priority: 5 },
    { id: 'fn-006', name: 'Return on Equity', domain: 'FINANCE', description: 'ROE metric', formulaTemplate: 'SUM(net_income) / AVG(equity)', aggregationRules: [{ function: 'SUM', column: 'net_income' }, { function: 'AVG', column: 'equity' }], defaultVisualizationHint: 'metric_card', requiredFields: ['net_income', 'equity'], columnAliases: { equity: ['shareholders_equity'] }, category: 'performance', priority: 6 },
    { id: 'fn-007', name: 'Non-performing Assets', domain: 'FINANCE', description: 'NPA ratio', formulaTemplate: 'SUM(npa) / SUM(total_loans)', aggregationRules: [{ function: 'SUM', column: 'npa' }, { function: 'SUM', column: 'total_loans' }], defaultVisualizationHint: 'metric_card', requiredFields: ['npa', 'total_loans'], columnAliases: { npa: ['bad_debt'] }, category: 'risk', priority: 7 },
    { id: 'fn-008', name: 'Liquidity Ratio', domain: 'FINANCE', description: 'Current ratio', formulaTemplate: 'SUM(current_assets) / SUM(current_liabilities)', aggregationRules: [{ function: 'SUM', column: 'current_assets' }, { function: 'SUM', column: 'current_liabilities' }], defaultVisualizationHint: 'metric_card', requiredFields: ['current_assets', 'current_liabilities'], columnAliases: {}, category: 'liquidity', priority: 8 },
    { id: 'fn-009', name: 'Interest Income', domain: 'FINANCE', description: 'Interest earned', formulaTemplate: 'SUM(interest_income)', aggregationRules: [{ function: 'SUM', column: 'interest_income' }], defaultVisualizationHint: 'metric_card', requiredFields: ['interest_income'], columnAliases: { interest_income: ['interest_earned'] }, category: 'revenue', priority: 9 },
    { id: 'fn-010', name: 'Fraud Rate', domain: 'FINANCE', description: 'Fraudulent transactions', formulaTemplate: 'COUNT(fraud) / COUNT(transaction_id)', aggregationRules: [{ function: 'COUNT', column: 'fraud' }, { function: 'COUNT', column: 'transaction_id' }], defaultVisualizationHint: 'metric_card', requiredFields: ['fraud', 'transaction_id'], columnAliases: { fraud: ['suspicious', 'flagged'] }, category: 'risk', priority: 10 },
];

export const FINANCE_KPIS = enrichKPIs(RAW_FINANCE_KPIS, 'FINANCE');

// Master library by domain
export const KPI_LIBRARY: Record<DomainType, KPIDefinition[]> = {
    ECOMMERCE: ECOMMERCE_KPIS,
    SAAS: SAAS_KPIS,
    EDTECH: EDTECH_KPIS,
    RETAIL: RETAIL_KPIS,
    SERVICES: SERVICES_KPIS,
    MANUFACTURING: MANUFACTURING_KPIS,
    HEALTHCARE: HEALTHCARE_KPIS,
    FINANCE: FINANCE_KPIS,
};

export function getKPIsForDomain(domain: DomainType): KPIDefinition[] {
    return KPI_LIBRARY[domain] || [];
}

export function getAllKPIs(): KPIDefinition[] {
    return Object.values(KPI_LIBRARY).flat();
}
